"""Seed — Activities catalog, Document Templates, 4x4 fleet enrichment.

Populates:
1. Morocco activities catalog (excursions, cultural, adventure, wellness)
2. S'TOURS document templates (voucher, reservation, information letter,
   appreciation forms, tips sheet, letterhead, fiche dossier)
3. 4x4 vehicle variants for desert excursions
"""
from __future__ import annotations

import sys, os
sys.path.insert(0, os.path.dirname(__file__))

# ── Safety guard ──────────────────────────────────────────────────────────────
from scripts._dev_guard import require_dev_env
require_dev_env('seed_activities_docs.py')
# ─────────────────────────────────────────────────────────────────────────────

# ── 1. MOROCCO ACTIVITIES CATALOG ─────────────────────────────────────────────
# Activities referenced in S'TOURS circuits: Sahara, Imperial Cities, Atlas, Coast

ACTIVITIES_CATALOG = [
    # Desert & Sahara
    {
        "code": "ACT-CAMEL-01",
        "name": "Balade en dromadaire — Merzouga",
        "name_i18n": {
            "fr": "Balade en dromadaire — Merzouga",
            "en": "Camel ride — Merzouga",
            "de": "Kamelritt — Merzouga",
            "it": "Giro in dromedario — Merzouga",
            "es": "Paseo en camello — Merzouga",
            "ja": "ラクダ乗り — メルズーガ",
            "zh": "骑骆驼 — 梅尔祖卡",
            "ko": "낙타 타기 — 메르주가",
        },
        "category": "excursion",
        "city": "Merzouga",
        "region": "Sahara",
        "duration_hours": 1.5,
        "cost_per_pax": 100,
        "currency": "MAD",
        "difficulty": "easy",
        "min_pax": 1,
        "max_pax": 50,
        "season": "all",
        "description_i18n": {
            "fr": "Traversée des dunes de l'Erg Chebbi au coucher du soleil. Départ du bivouac, montée sur les plus hautes dunes du Sahara marocain.",
            "en": "Cross the Erg Chebbi dunes at sunset. Depart from the bivouac and climb the highest dunes of the Moroccan Sahara.",
            "de": "Durchquerung der Erg-Chebbi-Dünen bei Sonnenuntergang. Abfahrt vom Biwak, Aufstieg zu den höchsten Dünen der marokkanischen Sahara.",
        },
        "included": ["guide", "camel", "tea"],
        "photo_tags": ["desert", "camel", "sunset", "sahara"],
    },
    {
        "code": "ACT-4X4-MERZ",
        "name": "Excursion 4×4 Sahara — Merzouga",
        "name_i18n": {
            "fr": "Excursion 4×4 Sahara — Merzouga",
            "en": "4×4 Sahara excursion — Merzouga",
            "de": "4×4 Sahara-Ausflug — Merzouga",
            "it": "Escursione 4×4 Sahara — Merzouga",
            "es": "Excursión 4×4 Sahara — Merzouga",
            "ja": "4×4サハラツアー — メルズーガ",
            "zh": "4×4撒哈拉之旅 — 梅尔祖卡",
            "ko": "4×4 사하라 투어 — 메르주가",
        },
        "category": "excursion",
        "city": "Merzouga",
        "region": "Sahara",
        "duration_hours": 3.0,
        "cost_per_pax": 280,
        "currency": "MAD",
        "difficulty": "moderate",
        "min_pax": 1,
        "max_pax": 4,
        "season": "all",
        "description_i18n": {
            "fr": "Circuit en 4×4 Toyota Land Cruiser dans le désert du Sahara. Visite des mines de plomb, villages nomades, oasis cachées et panoramas sur l'Erg Chebbi.",
            "en": "4×4 Toyota Land Cruiser circuit through the Sahara desert. Visit lead mines, nomad villages, hidden oases and panoramic views of Erg Chebbi.",
            "de": "4×4 Toyota Land Cruiser Rundfahrt durch die Sahara-Wüste. Besuch der Bleiminen, Nomadendörfer, versteckten Oasen und Panoramablicke auf den Erg Chebbi.",
        },
        "included": ["4x4_vehicle", "driver", "tea", "fossil_visit"],
        "photo_tags": ["4x4", "desert", "sahara", "offroad"],
    },
    {
        "code": "ACT-SAND-01",
        "name": "Sand-boarding — Erg Chebbi",
        "name_i18n": {
            "fr": "Sand-boarding — Erg Chebbi",
            "en": "Sand-boarding — Erg Chebbi",
            "de": "Sandboarden — Erg Chebbi",
            "it": "Sand-boarding — Erg Chebbi",
            "es": "Sand-boarding — Erg Chebbi",
            "ja": "サンドボーディング — エルグシェビ",
            "zh": "沙板滑行 — 厄尔格切比",
            "ko": "샌드보딩 — 에르그 셰비",
        },
        "category": "excursion",
        "city": "Merzouga",
        "region": "Sahara",
        "duration_hours": 1.0,
        "cost_per_pax": 50,
        "currency": "MAD",
        "difficulty": "moderate",
        "min_pax": 1,
        "max_pax": 20,
        "season": "all",
        "description_i18n": {
            "fr": "Descente des dunes de l'Erg Chebbi en sand-board. Sensations garanties sur les pentes de sable fin.",
            "en": "Slide down the Erg Chebbi dunes on a sand-board. Thrills guaranteed on the fine sand slopes.",
            "de": "Abfahrt von den Erg-Chebbi-Dünen auf einem Sandbrett. Nervenkitzel garantiert auf den feinen Sandhängen.",
        },
        "included": ["board", "instruction"],
        "photo_tags": ["sandboarding", "desert", "adventure"],
    },
    {
        "code": "ACT-BIVOUAC",
        "name": "Nuit en bivouac — Sahara",
        "name_i18n": {
            "fr": "Nuit en bivouac de luxe — Sahara",
            "en": "Luxury bivouac night — Sahara",
            "de": "Luxus-Biwak-Nacht — Sahara",
            "it": "Notte in bivacco di lusso — Sahara",
            "es": "Noche en vivac de lujo — Sahara",
            "ja": "ラグジュアリービバーク — サハラ",
            "zh": "豪华沙漠露营 — 撒哈拉",
            "ko": "럭셔리 비박 — 사하라",
        },
        "category": "excursion",
        "city": "Merzouga",
        "region": "Sahara",
        "duration_hours": 14.0,
        "cost_per_pax": 500,
        "currency": "MAD",
        "difficulty": "easy",
        "min_pax": 2,
        "max_pax": 40,
        "season": "sep-may",
        "description_i18n": {
            "fr": "Nuit sous les étoiles dans un camp de luxe au cœur des dunes. Dîner berbère traditionnel, musique gnaoua, feu de camp et petit-déjeuner au lever du soleil.",
            "en": "Night under the stars in a luxury camp amid the dunes. Traditional Berber dinner, Gnaoua music, campfire and sunrise breakfast.",
            "de": "Nacht unter den Sternen in einem Luxuscamp inmitten der Dünen. Traditionelles Berber-Abendessen, Gnaoua-Musik, Lagerfeuer und Frühstück bei Sonnenaufgang.",
        },
        "included": ["tent", "dinner", "breakfast", "music", "campfire"],
        "photo_tags": ["bivouac", "stars", "desert", "luxury"],
    },
    # Marrakech
    {
        "code": "ACT-CALECHE",
        "name": "Calèche — Marrakech",
        "name_i18n": {
            "fr": "Tour en calèche — Marrakech",
            "en": "Horse carriage ride — Marrakech",
            "de": "Pferdekutschenfahrt — Marrakesch",
            "it": "Giro in carrozza — Marrakech",
            "es": "Paseo en coche de caballos — Marrakech",
            "ja": "馬車ツアー — マラケシュ",
            "zh": "马车游览 — 马拉喀什",
            "ko": "마차 투어 — 마라케시",
        },
        "category": "excursion",
        "city": "Marrakech",
        "region": "Marrakech-Safi",
        "duration_hours": 2.0,
        "cost_per_pax": 100,
        "currency": "MAD",
        "difficulty": "easy",
        "min_pax": 1,
        "max_pax": 4,
        "season": "all",
        "description_i18n": {
            "fr": "Tour de la ville en calèche traditionnelle. Passage par les remparts, la Koutoubia, les jardins de la Ménara et le quartier de l'Hivernage.",
            "en": "City tour by traditional horse carriage. Pass by the ramparts, Koutoubia Mosque, Menara Gardens and the Hivernage district.",
            "de": "Stadtrundfahrt in einer traditionellen Pferdekutsche. Vorbei an den Stadtmauern, der Koutoubia-Moschee, den Menara-Gärten und dem Hivernage-Viertel.",
        },
        "included": ["carriage", "driver"],
        "photo_tags": ["carriage", "marrakech", "koutoubia"],
    },
    {
        "code": "ACT-COOK-RAK",
        "name": "Cours de cuisine — Marrakech",
        "name_i18n": {
            "fr": "Cours de cuisine marocaine — Marrakech",
            "en": "Moroccan cooking class — Marrakech",
            "de": "Marokkanischer Kochkurs — Marrakesch",
            "it": "Corso di cucina marocchina — Marrakech",
            "es": "Clase de cocina marroquí — Marrakech",
            "ja": "モロッコ料理教室 — マラケシュ",
            "zh": "摩洛哥烹饪课 — 马拉喀什",
            "ko": "모로코 요리 교실 — 마라케시",
        },
        "category": "excursion",
        "city": "Marrakech",
        "region": "Marrakech-Safi",
        "duration_hours": 3.0,
        "cost_per_pax": 350,
        "currency": "MAD",
        "difficulty": "easy",
        "min_pax": 2,
        "max_pax": 15,
        "season": "all",
        "description_i18n": {
            "fr": "Visite du souk aux épices, sélection des ingrédients, puis cours de cuisine dans un riad traditionnel. Préparation de tagine, couscous et pâtisseries marocaines.",
            "en": "Visit the spice souk, select ingredients, then cooking class in a traditional riad. Prepare tagine, couscous and Moroccan pastries.",
            "de": "Besuch des Gewürzmarktes, Zutatenauswahl, dann Kochkurs in einem traditionellen Riad. Zubereitung von Tagine, Couscous und marokkanischem Gebäck.",
        },
        "included": ["ingredients", "chef_instructor", "recipe_booklet", "meal"],
        "photo_tags": ["cooking", "tagine", "souk", "riad"],
    },
    {
        "code": "ACT-CHEZ-ALI",
        "name": "Dîner-spectacle Chez Ali — Marrakech",
        "name_i18n": {
            "fr": "Dîner-spectacle Chez Ali — Marrakech",
            "en": "Dinner show Chez Ali — Marrakech",
            "de": "Dinner-Show Chez Ali — Marrakesch",
            "it": "Cena-spettacolo Chez Ali — Marrakech",
            "es": "Cena-espectáculo Chez Ali — Marrakech",
            "ja": "ディナーショー シェ・アリ — マラケシュ",
            "zh": "阿里之家晚宴秀 — 马拉喀什",
            "ko": "셰 알리 디너쇼 — 마라케시",
        },
        "category": "excursion",
        "city": "Marrakech",
        "region": "Marrakech-Safi",
        "duration_hours": 3.5,
        "cost_per_pax": 400,
        "currency": "MAD",
        "difficulty": "easy",
        "min_pax": 1,
        "max_pax": 200,
        "season": "all",
        "description_i18n": {
            "fr": "Dîner sous les étoiles dans un complexe fantasia avec spectacle équestre, acrobates, danseuses et feu d'artifice.",
            "en": "Dinner under the stars in a fantasia complex with equestrian show, acrobats, dancers and fireworks.",
            "de": "Abendessen unter den Sternen in einem Fantasia-Komplex mit Reitshow, Akrobaten, Tänzern und Feuerwerk.",
        },
        "included": ["dinner", "show", "transport"],
        "photo_tags": ["chez_ali", "fantasia", "marrakech"],
    },
    {
        "code": "ACT-BALLOON",
        "name": "Montgolfière — Marrakech",
        "name_i18n": {
            "fr": "Vol en montgolfière — Marrakech",
            "en": "Hot air balloon flight — Marrakech",
            "de": "Heißluftballonfahrt — Marrakesch",
            "it": "Volo in mongolfiera — Marrakech",
            "es": "Vuelo en globo — Marrakech",
            "ja": "熱気球フライト — マラケシュ",
            "zh": "热气球飞行 — 马拉喀什",
            "ko": "열기구 비행 — 마라케시",
        },
        "category": "excursion",
        "city": "Marrakech",
        "region": "Marrakech-Safi",
        "duration_hours": 3.0,
        "cost_per_pax": 1800,
        "currency": "MAD",
        "difficulty": "easy",
        "min_pax": 2,
        "max_pax": 8,
        "season": "all",
        "description_i18n": {
            "fr": "Vol au lever du soleil au-dessus de la palmeraie de Marrakech et des montagnes de l'Atlas. Petit-déjeuner berbère à l'atterrissage.",
            "en": "Sunrise flight over the Marrakech palm grove and Atlas Mountains. Berber breakfast upon landing.",
            "de": "Sonnenaufgangsflug über die Palmenzone von Marrakesch und das Atlasgebirge. Berber-Frühstück nach der Landung.",
        },
        "included": ["flight", "breakfast", "certificate", "photos"],
        "photo_tags": ["balloon", "atlas", "sunrise", "palmeraie"],
    },
    {
        "code": "ACT-HAMMAM",
        "name": "Hammam & Spa traditionnel",
        "name_i18n": {
            "fr": "Hammam & Spa traditionnel",
            "en": "Traditional Hammam & Spa",
            "de": "Traditionelles Hammam & Spa",
            "it": "Hammam & Spa tradizionale",
            "es": "Hammam y Spa tradicional",
            "ja": "伝統的ハマム＆スパ",
            "zh": "传统哈玛姆水疗",
            "ko": "전통 하맘 & 스파",
        },
        "category": "excursion",
        "city": "Marrakech",
        "region": "Marrakech-Safi",
        "duration_hours": 2.0,
        "cost_per_pax": 400,
        "currency": "MAD",
        "difficulty": "easy",
        "min_pax": 1,
        "max_pax": 10,
        "season": "all",
        "description_i18n": {
            "fr": "Séance de hammam traditionnel avec gommage au savon noir, masque à l'argile du Ghassoul et massage à l'huile d'argan.",
            "en": "Traditional hammam session with black soap scrub, Ghassoul clay mask and argan oil massage.",
            "de": "Traditionelle Hammam-Sitzung mit schwarzem Seifenpeeling, Ghassoul-Tonmaske und Arganöl-Massage.",
        },
        "included": ["hammam", "scrub", "mask", "massage", "tea"],
        "photo_tags": ["hammam", "spa", "wellness"],
    },
    # Fès
    {
        "code": "ACT-MEDINA-FES",
        "name": "Visite guidée Médina — Fès",
        "name_i18n": {
            "fr": "Visite guidée de la Médina — Fès",
            "en": "Guided Medina tour — Fes",
            "de": "Geführte Medina-Tour — Fes",
            "it": "Tour guidato della Medina — Fes",
            "es": "Tour guiado de la Medina — Fez",
            "ja": "メディナガイドツアー — フェズ",
            "zh": "非斯老城导览 — 非斯",
            "ko": "메디나 가이드 투어 — 페스",
        },
        "category": "excursion",
        "city": "Fes",
        "region": "Fes-Meknes",
        "duration_hours": 4.0,
        "cost_per_pax": 100,
        "currency": "MAD",
        "difficulty": "moderate",
        "min_pax": 1,
        "max_pax": 20,
        "season": "all",
        "description_i18n": {
            "fr": "Visite de la plus grande médina du monde : Médersa Bou Inania, tanneries Chouara, souks artisanaux, poterie de Fès, Karaouiyine.",
            "en": "Visit the world's largest medina: Bou Inania Madrasa, Chouara tanneries, artisan souks, Fes pottery, Karaouiyine.",
            "de": "Besuch der größten Medina der Welt: Bou-Inania-Madrasa, Chouara-Gerbereien, Handwerksmärkte, Fes-Keramik, Karaouiyine.",
        },
        "included": ["local_guide", "monuments_entrance"],
        "photo_tags": ["medina", "fes", "tanneries", "madrasa"],
    },
    # Chefchaouen
    {
        "code": "ACT-CHEF-WALK",
        "name": "Randonnée — Chefchaouen",
        "name_i18n": {
            "fr": "Randonnée dans le Rif — Chefchaouen",
            "en": "Rif mountain hike — Chefchaouen",
            "de": "Rif-Gebirgswanderung — Chefchaouen",
            "it": "Trekking nel Rif — Chefchaouen",
            "es": "Senderismo en el Rif — Chefchaouen",
            "ja": "リフ山脈ハイキング — シェフシャウエン",
            "zh": "里夫山徒步 — 舍夫沙万",
            "ko": "리프 산맥 하이킹 — 셰프샤우엔",
        },
        "category": "excursion",
        "city": "Chefchaouen",
        "region": "Tanger-Tetouan-Al Hoceima",
        "duration_hours": 3.0,
        "cost_per_pax": 80,
        "currency": "MAD",
        "difficulty": "moderate",
        "min_pax": 2,
        "max_pax": 15,
        "season": "mar-nov",
        "description_i18n": {
            "fr": "Randonnée dans les montagnes du Rif depuis la cascade d'Akchour. Sentier panoramique avec vue sur la ville bleue.",
            "en": "Hike in the Rif mountains from Akchour waterfall. Panoramic trail with views of the blue city.",
            "de": "Wanderung im Rif-Gebirge vom Akchour-Wasserfall aus. Panoramapfad mit Blick auf die blaue Stadt.",
        },
        "included": ["local_guide", "water"],
        "photo_tags": ["chefchaouen", "rif", "waterfall", "blue_city"],
    },
    # Atlas
    {
        "code": "ACT-QUAD-PALM",
        "name": "Quad dans la palmeraie — Marrakech",
        "name_i18n": {
            "fr": "Quad dans la palmeraie — Marrakech",
            "en": "Quad biking in the palm grove — Marrakech",
            "de": "Quadfahrt in der Palmenzone — Marrakesch",
            "it": "Quad nella palmeria — Marrakech",
            "es": "Quad en el palmeral — Marrakech",
            "ja": "クワッドバイク — マラケシュ",
            "zh": "沙漠越野车 — 马拉喀什",
            "ko": "쿼드바이크 — 마라케시",
        },
        "category": "excursion",
        "city": "Marrakech",
        "region": "Marrakech-Safi",
        "duration_hours": 2.0,
        "cost_per_pax": 450,
        "currency": "MAD",
        "difficulty": "moderate",
        "min_pax": 1,
        "max_pax": 10,
        "season": "all",
        "description_i18n": {
            "fr": "Circuit en quad à travers la palmeraie de Marrakech et les villages berbères. Pause thé chez l'habitant.",
            "en": "Quad circuit through the Marrakech palm grove and Berber villages. Tea break at a local home.",
            "de": "Quad-Tour durch die Palmenzone von Marrakesch und Berberdörfer. Teepause bei Einheimischen.",
        },
        "included": ["quad", "helmet", "goggles", "tea", "guide"],
        "photo_tags": ["quad", "palmeraie", "adventure"],
    },
    {
        "code": "ACT-OURIKA",
        "name": "Excursion Vallée de l'Ourika",
        "name_i18n": {
            "fr": "Excursion Vallée de l'Ourika",
            "en": "Ourika Valley excursion",
            "de": "Ausflug ins Ourika-Tal",
            "it": "Escursione nella Valle dell'Ourika",
            "es": "Excursión al Valle del Ourika",
            "ja": "ウリカ渓谷ツアー",
            "zh": "乌里卡谷之旅",
            "ko": "우리카 계곡 투어",
        },
        "category": "excursion",
        "city": "Ourika",
        "region": "Marrakech-Safi",
        "duration_hours": 6.0,
        "cost_per_pax": 250,
        "currency": "MAD",
        "difficulty": "moderate",
        "min_pax": 2,
        "max_pax": 20,
        "season": "all",
        "description_i18n": {
            "fr": "Journée dans la vallée de l'Ourika au pied de l'Atlas. Visite de coopératives d'argan, villages berbères et cascades.",
            "en": "Full day in the Ourika Valley at the foot of the Atlas. Visit argan cooperatives, Berber villages and waterfalls.",
            "de": "Ganztagesausflug ins Ourika-Tal am Fuße des Atlas. Besuch von Argan-Kooperativen, Berberdörfern und Wasserfällen.",
        },
        "included": ["transport", "guide", "lunch"],
        "photo_tags": ["ourika", "atlas", "waterfall", "berber"],
    },
    # Essaouira
    {
        "code": "ACT-ESSAOUIRA",
        "name": "Excursion Essaouira — Côte Atlantique",
        "name_i18n": {
            "fr": "Excursion Essaouira — Côte Atlantique",
            "en": "Essaouira excursion — Atlantic Coast",
            "de": "Ausflug Essaouira — Atlantikküste",
            "it": "Escursione Essaouira — Costa Atlantica",
            "es": "Excursión Essaouira — Costa Atlántica",
            "ja": "エッサウィラ — 大西洋沿岸",
            "zh": "索维拉之旅 — 大西洋海岸",
            "ko": "에사우이라 — 대서양 해안",
        },
        "category": "excursion",
        "city": "Essaouira",
        "region": "Marrakech-Safi",
        "duration_hours": 10.0,
        "cost_per_pax": 300,
        "currency": "MAD",
        "difficulty": "easy",
        "min_pax": 2,
        "max_pax": 40,
        "season": "all",
        "description_i18n": {
            "fr": "Journée à Essaouira, cité portuaire classée UNESCO. Visite de la médina, port de pêche, galeries d'art et déjeuner de poisson frais.",
            "en": "Full day in Essaouira, UNESCO-listed port city. Visit the medina, fishing port, art galleries and fresh fish lunch.",
            "de": "Ganztag in Essaouira, UNESCO-gelistete Hafenstadt. Besuch der Medina, Fischereihafen, Kunstgalerien und frisches Fischessen.",
        },
        "included": ["transport", "guide", "lunch"],
        "photo_tags": ["essaouira", "atlantic", "port", "medina"],
    },
    # ── NEW — From BDD MEDIA/Activités OneDrive ──────────────────────
    {
        "code": "ACT-NAUTIQUE",
        "name": "Activités nautiques — Agadir",
        "name_i18n": {
            "fr": "Activités nautiques — Agadir", "en": "Water sports — Agadir",
            "de": "Wassersport — Agadir", "it": "Sport acquatici — Agadir",
            "es": "Deportes acuáticos — Agadir", "ja": "マリンスポーツ — アガディール",
            "zh": "水上运动 — 阿加迪尔", "ko": "수상 스포츠 — 아가디르",
        },
        "category": "adventure",
        "city": "Agadir", "region": "Souss-Massa",
        "duration_hours": 2.0, "cost_per_pax": 350, "currency": "MAD",
        "difficulty": "moderate", "min_pax": 1, "max_pax": 10, "season": "all",
        "description_i18n": {
            "fr": "Jet-ski, kayak, paddle et windsurf sur la baie d'Agadir.",
            "en": "Jet-ski, kayak, paddle and windsurfing on Agadir bay.",
            "de": "Jetski, Kajak, Paddeln und Windsurfen in der Bucht von Agadir.",
        },
        "included": ["equipment", "instructor", "insurance"],
        "photo_tags": ["nautique", "jet_ski", "windsurf", "agadir"],
        "photos_folder": "Activités Nautiques",
    },
    {
        "code": "ACT-AIR",
        "name": "Air Sensation — Parapente",
        "name_i18n": {
            "fr": "Air Sensation — Parapente", "en": "Air Sensation — Paragliding",
            "de": "Air Sensation — Gleitschirmfliegen", "it": "Parapendio",
            "es": "Parapente", "ja": "パラグライダー", "zh": "滑翔伞", "ko": "패러글라이딩",
        },
        "category": "adventure",
        "city": "Agadir", "region": "Souss-Massa",
        "duration_hours": 1.5, "cost_per_pax": 800, "currency": "MAD",
        "difficulty": "moderate", "min_pax": 1, "max_pax": 2, "season": "all",
        "description_i18n": {
            "fr": "Vol en parapente au-dessus de la côte atlantique avec instructeur certifié.",
            "en": "Paragliding flight over the Atlantic coast with certified instructor.",
            "de": "Gleitschirmflug über die Atlantikküste mit zertifiziertem Lehrer.",
        },
        "included": ["flight", "instructor", "photos", "insurance"],
        "photo_tags": ["paragliding", "air", "coast"],
        "photos_folder": "Air Sensation",
    },
    {
        "code": "ACT-ARGAN",
        "name": "Visite coopérative d'argan",
        "name_i18n": {
            "fr": "Visite coopérative d'argan", "en": "Argan oil cooperative visit",
            "de": "Besuch einer Arganöl-Kooperative", "it": "Visita cooperativa olio di argan",
            "es": "Visita cooperativa de argán", "ja": "アルガンオイル工房見学",
            "zh": "摩洛哥坚果油工坊参观", "ko": "아르간 오일 협동조합 방문",
        },
        "category": "cultural",
        "city": "Essaouira", "region": "Marrakech-Safi",
        "duration_hours": 1.0, "cost_per_pax": 0, "currency": "MAD",
        "difficulty": "easy", "min_pax": 1, "max_pax": 50, "season": "all",
        "description_i18n": {
            "fr": "Visite d'une coopérative féminine d'huile d'argan. Processus traditionnel.",
            "en": "Visit a women's cooperative producing argan oil. Traditional process.",
            "de": "Besuch einer Frauenkooperative zur Arganölproduktion.",
        },
        "included": ["guide", "tasting"],
        "photo_tags": ["argan", "cooperative", "women", "oil"],
        "photos_folder": "Argan Oil",
    },
    {
        "code": "ACT-EBIKE",
        "name": "E-Bike désert Agafay",
        "name_i18n": {
            "fr": "E-Bike désert Agafay", "en": "E-Bike Agafay desert",
            "de": "E-Bike Agafay-Wüste", "it": "E-Bike deserto Agafay",
            "es": "E-Bike desierto Agafay", "ja": "E-バイク アガファイ砂漠",
            "zh": "电动自行车 阿加法伊沙漠", "ko": "전기자전거 아가파이 사막",
        },
        "category": "adventure",
        "city": "Marrakech", "region": "Marrakech-Safi",
        "duration_hours": 3.0, "cost_per_pax": 600, "currency": "MAD",
        "difficulty": "moderate", "min_pax": 2, "max_pax": 10, "season": "all",
        "description_i18n": {
            "fr": "Randonnée en vélo électrique dans le désert d'Agafay.",
            "en": "E-bike ride through Agafay desert, on the doorstep of Marrakech.",
            "de": "E-Bike-Tour durch die Agafay-Wüste, vor den Toren von Marrakesch.",
        },
        "included": ["e_bike", "helmet", "guide", "water", "snack"],
        "photo_tags": ["ebike", "agafay", "desert", "cycling"],
        "photos_folder": "EBike Agafay",
    },
    {
        "code": "ACT-FOOD-TOUR",
        "name": "Food tasting tour — Marrakech",
        "name_i18n": {
            "fr": "Tour gastronomique — Marrakech", "en": "Food tasting tour — Marrakech",
            "de": "Kulinarische Tour — Marrakesch", "it": "Tour gastronomico — Marrakech",
            "es": "Tour gastronómico — Marrakech", "ja": "フードツアー — マラケシュ",
            "zh": "美食之旅 — 马拉喀什", "ko": "푸드 투어 — 마라케시",
        },
        "category": "gastronomy",
        "city": "Marrakech", "region": "Marrakech-Safi",
        "duration_hours": 3.0, "cost_per_pax": 350, "currency": "MAD",
        "difficulty": "easy", "min_pax": 2, "max_pax": 12, "season": "all",
        "description_i18n": {
            "fr": "Découverte des saveurs marocaines : souks, épices, pâtisseries, street food.",
            "en": "Discover Moroccan flavors: souks, spices, pastries, street food.",
            "de": "Marokkanische Aromen entdecken: Souks, Gewürze, Gebäck, Straßenessen.",
        },
        "included": ["guide", "tastings", "water"],
        "photo_tags": ["food", "souk", "spices", "medina"],
        "photos_folder": "Food Tasting Tour",
    },
    {
        "code": "ACT-PERFUME",
        "name": "Atelier parfum — Marrakech",
        "name_i18n": {
            "fr": "Atelier parfum — Marrakech", "en": "Perfume workshop — Marrakech",
            "de": "Parfüm-Workshop — Marrakesch", "it": "Laboratorio profumi — Marrakech",
            "es": "Taller de perfumes — Marrakech", "ja": "香水ワークショップ — マラケシュ",
            "zh": "香水工坊 — 马拉喀什", "ko": "향수 워크숍 — 마라케시",
        },
        "category": "cultural",
        "city": "Marrakech", "region": "Marrakech-Safi",
        "duration_hours": 1.5, "cost_per_pax": 300, "currency": "MAD",
        "difficulty": "easy", "min_pax": 2, "max_pax": 10, "season": "all",
        "description_i18n": {
            "fr": "Création de votre propre parfum : rose, jasmin, ambre, musc.",
            "en": "Create your own perfume with Moroccan essences: rose, jasmine, amber, musk.",
            "de": "Kreieren Sie Ihr eigenes Parfüm mit marokkanischen Essenzen.",
        },
        "included": ["essences", "bottle", "instructor"],
        "photo_tags": ["perfume", "workshop", "essences"],
        "photos_folder": "Perfume Workshop",
    },
    {
        "code": "ACT-POTTERY",
        "name": "Atelier poterie — Fès / Safi",
        "name_i18n": {
            "fr": "Atelier poterie — Fès / Safi", "en": "Pottery workshop — Fes / Safi",
            "de": "Töpfer-Workshop — Fes / Safi", "it": "Laboratorio ceramica — Fes / Safi",
            "es": "Taller de cerámica — Fez / Safi", "ja": "陶芸ワークショップ — フェズ",
            "zh": "陶艺工坊 — 非斯", "ko": "도자기 워크숍 — 페스",
        },
        "category": "cultural",
        "city": "Fes", "region": "Fes-Meknes",
        "duration_hours": 2.0, "cost_per_pax": 200, "currency": "MAD",
        "difficulty": "easy", "min_pax": 2, "max_pax": 10, "season": "all",
        "description_i18n": {
            "fr": "Initiation à la poterie traditionnelle. Tour de potier, émaillage, peinture.",
            "en": "Introduction to traditional pottery. Potter's wheel, glazing, painting.",
            "de": "Einführung in die traditionelle Töpferei. Töpferscheibe, Glasur, Malerei.",
        },
        "included": ["clay", "instructor", "finished_piece"],
        "photo_tags": ["pottery", "ceramics", "artisan", "fes"],
        "photos_folder": "Poterie",
    },
    {
        "code": "ACT-SIDECAR",
        "name": "Tour en sidecar vintage — Marrakech",
        "name_i18n": {
            "fr": "Tour en sidecar vintage — Marrakech", "en": "Vintage sidecar tour — Marrakech",
            "de": "Vintage Sidecar-Tour — Marrakesch", "it": "Tour in sidecar vintage — Marrakech",
            "es": "Tour en sidecar vintage — Marrakech", "ja": "サイドカーツアー — マラケシュ",
            "zh": "复古挎斗摩托车之旅 — 马拉喀什", "ko": "사이드카 투어 — 마라케시",
        },
        "category": "adventure",
        "city": "Marrakech", "region": "Marrakech-Safi",
        "duration_hours": 2.0, "cost_per_pax": 500, "currency": "MAD",
        "difficulty": "easy", "min_pax": 1, "max_pax": 2, "season": "all",
        "description_i18n": {
            "fr": "Tour de Marrakech en sidecar Ural vintage. Médina, Majorelle, Palmeraie.",
            "en": "Tour Marrakech in a vintage Ural sidecar. Medina, Majorelle, Palm grove.",
            "de": "Tour durch Marrakesch im Vintage-Ural-Seitenwagen.",
        },
        "included": ["sidecar", "driver", "goggles", "helmet"],
        "photo_tags": ["sidecar", "vintage", "marrakech"],
        "photos_folder": "SideCar",
    },
    {
        "code": "ACT-SKY-DINNER",
        "name": "Sky Dinner — Marrakech",
        "name_i18n": {
            "fr": "Sky Dinner — Marrakech", "en": "Sky Dinner — Marrakech",
            "de": "Sky Dinner — Marrakesch", "it": "Sky Dinner — Marrakech",
            "es": "Sky Dinner — Marrakech", "ja": "スカイディナー — マラケシュ",
            "zh": "空中晚宴 — 马拉喀什", "ko": "스카이 디너 — 마라케시",
        },
        "category": "entertainment",
        "city": "Marrakech", "region": "Marrakech-Safi",
        "duration_hours": 2.0, "cost_per_pax": 1500, "currency": "MAD",
        "difficulty": "easy", "min_pax": 12, "max_pax": 22, "season": "all",
        "description_i18n": {
            "fr": "Dîner suspendu à 50m dans les airs avec vue panoramique sur Marrakech et l'Atlas.",
            "en": "Dinner suspended 50m in the air with panoramic views of Marrakech and the Atlas.",
            "de": "Abendessen in 50m Höhe mit Panoramablick auf Marrakesch und den Atlas.",
        },
        "included": ["dinner_4_courses", "drinks", "photos", "entertainment"],
        "photo_tags": ["sky_dinner", "suspended", "panoramic", "luxury"],
        "photos_folder": "Sky Dinner",
    },
    {
        "code": "ACT-WINE",
        "name": "Dégustation de vin — Meknès",
        "name_i18n": {
            "fr": "Dégustation de vin — Meknès", "en": "Wine tasting — Meknes",
            "de": "Weinverkostung — Meknes", "it": "Degustazione vini — Meknes",
            "es": "Cata de vinos — Meknes", "ja": "ワインテイスティング — メクネス",
            "zh": "品酒 — 梅克内斯", "ko": "와인 시음 — 메크네스",
        },
        "category": "gastronomy",
        "city": "Meknes", "region": "Fes-Meknes",
        "duration_hours": 2.0, "cost_per_pax": 250, "currency": "MAD",
        "difficulty": "easy", "min_pax": 2, "max_pax": 20, "season": "all",
        "description_i18n": {
            "fr": "Visite des vignobles de Meknès et dégustation des vins marocains (AOG Guerrouane).",
            "en": "Visit Meknes vineyards and taste Moroccan wines (AOG Guerrouane).",
            "de": "Besuch der Weingüter von Meknes und Verkostung marokkanischer Weine.",
        },
        "included": ["wine_tasting", "guide", "cheese_board"],
        "photo_tags": ["wine", "vineyard", "meknes", "tasting"],
        "photos_folder": "Wine Tasting",
    },
    {
        "code": "ACT-ZELLIGE",
        "name": "Atelier zellige — Fès / Rabat",
        "name_i18n": {
            "fr": "Atelier zellige — Fès / Rabat", "en": "Zellige mosaic workshop — Fes / Rabat",
            "de": "Zellige-Mosaik-Workshop — Fes / Rabat", "it": "Laboratorio zellige — Fes / Rabat",
            "es": "Taller de zellige — Fez / Rabat", "ja": "ゼリージュモザイク体験 — フェズ",
            "zh": "马赛克工艺体验 — 非斯", "ko": "젤리주 모자이크 워크숍 — 페스",
        },
        "category": "cultural",
        "city": "Fes", "region": "Fes-Meknes",
        "duration_hours": 2.5, "cost_per_pax": 250, "currency": "MAD",
        "difficulty": "easy", "min_pax": 2, "max_pax": 8, "season": "all",
        "description_i18n": {
            "fr": "Initiation à l'art du zellige : découpe, assemblage et pose de mosaïque.",
            "en": "Introduction to zellige art: cutting, assembly and laying mosaic tiles.",
            "de": "Einführung in die Zellige-Kunst: Schneiden, Zusammensetzen und Verlegen.",
        },
        "included": ["materials", "instructor", "tea", "finished_piece"],
        "photo_tags": ["zellige", "mosaic", "artisan", "fes"],
        "photos_folder": "Zelige",
    },
]


# ── 2. S'TOURS DOCUMENT TEMPLATES ────────────────────────────────────────────

DOCUMENT_TEMPLATES = [
    {
        "code": "voucher",
        "name": "Bon de Service / Voucher",
        "name_i18n": {
            "fr": "Bon de Service", "en": "Service Voucher",
            "de": "Dienstleistungsgutschein", "it": "Buono di Servizio",
            "es": "Bono de Servicio",
        },
        "category": "operational",
        "language": "fr",
        "description": "Bon de service envoyé aux prestataires (hôtels, restaurants, transport) confirmant les services réservés pour un groupe.",
        "fields": {
            "dossier_ref": "string",
            "voucher_number": "string",
            "supplier_name": "string",
            "supplier_city": "string",
            "client_group": "string",
            "pax_count": "number",
            "rooms": {"single": "number", "double": "number", "triple": "number", "total": "number"},
            "dates": {"checkin": "date", "checkout": "date"},
            "meals": {"breakfast": "boolean", "lunch": "boolean", "dinner": "boolean"},
            "board_type": "string",
            "transport": {"type": "string", "pickup": "string", "dropoff": "string"},
            "observations": "string",
        },
    },
    {
        "code": "reservation",
        "name": "Demande de Réservation",
        "name_i18n": {
            "fr": "Demande de Réservation", "en": "Reservation Request",
            "de": "Reservierungsanfrage", "it": "Richiesta di Prenotazione",
            "es": "Solicitud de Reserva",
        },
        "category": "operational",
        "language": "fr",
        "description": "Formulaire de demande de réservation envoyé par fax/email aux fournisseurs pour confirmer les disponibilités.",
        "fields": {
            "from_company": "string",
            "to_supplier": "string",
            "date": "date",
            "client_names": "string[]",
            "room_requirements": "string",
            "special_requests": "string",
        },
    },
    {
        "code": "information_letter",
        "name": "Information Letter / Lettre d'information",
        "name_i18n": {
            "fr": "Lettre d'information client", "en": "Client Information Letter",
            "de": "Kundeninformationsschreiben", "it": "Lettera informativa",
            "es": "Carta informativa",
        },
        "category": "client_facing",
        "language": "en",
        "description": "Lettre d'information remise au client avec les détails du circuit : hôtels, contacts, restaurants, services inclus jour par jour.",
        "fields": {
            "tour_ref": "string",
            "services_provider": "string",
            "emergency_contact": "string",
            "accommodation_summary": "string",
            "daily_details": [{"day": "date", "city": "string", "hotel": "string", "hotel_phone": "string", "meals": "string"}],
        },
    },
    {
        "code": "appreciation_en",
        "name": "Appreciation Form (English)",
        "name_i18n": {
            "fr": "Fiche d'appréciation (anglais)", "en": "Appreciation Form",
            "de": "Bewertungsbogen (Englisch)", "it": "Scheda di valutazione (inglese)",
            "es": "Ficha de valoración (inglés)",
        },
        "category": "client_facing",
        "language": "en",
        "description": "Formulaire de satisfaction client en anglais. Évalue guide, chauffeur, bus, hôtels (accueil, hébergement, restauration) par ville.",
        "fields": {
            "client_name": "string", "country": "string", "city": "string",
            "agency": "string", "phone": "string",
            "ratings": {
                "tour_guide": "excellent|good|to_improve",
                "driver": "excellent|good|to_improve",
                "motorcoach": "excellent|good|to_improve",
                "hotels": [{"city": "string", "welcome": "rating", "accommodation": "rating", "food": "rating", "restaurant": "rating"}],
            },
            "general_remarks": "string",
        },
    },
    {
        "code": "appreciation_de",
        "name": "Bewertungsbogen (Deutsch)",
        "name_i18n": {
            "fr": "Fiche d'appréciation (allemand)", "en": "Appreciation Form (German)",
            "de": "Bewertungsbogen", "it": "Scheda di valutazione (tedesco)",
            "es": "Ficha de valoración (alemán)",
        },
        "category": "client_facing",
        "language": "de",
        "description": "Fragebogen zur Kundenzufriedenheit auf Deutsch. Bewertung von Reiseleiter, Fahrer, Bus, Hotels pro Stadt.",
        "fields": {
            "client_name": "string", "beruf": "string", "anschrift": "string",
            "agentur": "string", "tel": "string",
            "bewertungen": {
                "reiseleiter": "ausgezeichnet|gut|mittel|schlecht",
                "busfahrer": "ausgezeichnet|gut|mittel|schlecht",
                "bus": "ausgezeichnet|gut|mittel|schlecht",
                "hotels": [{"stadt": "string", "empfang": "rating", "unterkunft": "rating", "mahlzeiten": "rating", "stadtfuehrer": "rating", "restaurant": "rating"}],
            },
            "anmerkungen": "string",
        },
    },
    {
        "code": "tips_sheet",
        "name": "Feuille des Pourboires",
        "name_i18n": {
            "fr": "Feuille des pourboires", "en": "Tips Tracking Sheet",
            "de": "Trinkgeld-Übersicht", "it": "Foglio mance",
            "es": "Hoja de propinas",
        },
        "category": "internal",
        "language": "fr",
        "description": "Fiche de suivi des pourboires par jour : aéroport (porteurs), hôtel (bagagiste), restaurant. Signée par le guide avec cachet.",
        "fields": {
            "group_name": "string", "dossier_ref": "string",
            "date_passage": "date", "pax_count": "number",
            "guide": "string", "chauffeur": "string",
            "daily_tips": [{"date": "date", "airport_porters": "number", "hotel_bellboy": "number", "restaurant": "number", "total": "number", "signature": "string"}],
        },
    },
    {
        "code": "fiche_dossier",
        "name": "Fiche Dossier",
        "name_i18n": {
            "fr": "Fiche dossier", "en": "File Card",
            "de": "Aktenblatt", "it": "Scheda fascicolo",
            "es": "Ficha de expediente",
        },
        "category": "internal",
        "language": "fr",
        "description": "Fiche récapitulative du dossier voyage : client, dates, PAX, hôtels, transport, guide, services spéciaux.",
        "fields": {
            "dossier_ref": "string", "client": "string",
            "agency": "string", "arrival_date": "date",
            "departure_date": "date", "pax": "number",
            "hotels": "string[]", "transport_type": "string",
            "guide_name": "string", "special_services": "string",
        },
    },
    {
        "code": "letterhead",
        "name": "En-tête S'TOURS",
        "name_i18n": {
            "fr": "En-tête S'TOURS", "en": "S'TOURS Letterhead",
            "de": "S'TOURS Briefkopf", "it": "Intestazione S'TOURS",
            "es": "Membrete S'TOURS",
        },
        "category": "branding",
        "language": "fr",
        "description": "En-tête officiel S'TOURS avec logo, adresse (4 rue Turgot, Quartier Racine, 20100 Casablanca), téléphone et fax.",
        "fields": {
            "company_name": "S'TOURS",
            "address": "4, rue Turgot - Quartier Racine - 20100 Casablanca",
            "phone": "+212 522 36 13 04 / 522 36 07 73",
            "fax": "+212 522 36 20 35",
            "email": "dmc@stoursvoyages.com",
            "website": "www.stours.co.ma",
        },
    },
]


# ── 3. 4×4 VEHICLE VARIANTS ──────────────────────────────────────────────────
# The existing fleet has one generic 4x4 Land Cruiser.
# Add specific variants used in S'TOURS operations.

VEHICLE_4X4_ADDITIONS = [
    {
        "label": "4×4 Toyota Land Cruiser — Sahara",
        "type": "4wd",
        "capacity_min": 1,
        "capacity_max": 4,
        "brand_models": "Toyota Land Cruiser Prado",
        "rate_per_km": 15.0,
        "rate_per_day": 1800.0,
        "currency": "MAD",
        "specs": {
            "ac": True, "wifi": False, "off_road": True,
            "ratio_pax_per_vehicle": 4,
            "use_cases": ["Sahara", "Merzouga", "Erg Chebbi", "Zagora"],
            "luggage_capacity": "Large",
            "desert_ready": True,
        },
        "notes": "Référence S'TOURS pour les excursions Sahara. Robuste, climatisé, capacité bagages.",
    },
    {
        "label": "4×4 Toyota Hilux — Désert",
        "type": "4wd",
        "capacity_min": 1,
        "capacity_max": 3,
        "brand_models": "Toyota Hilux Double Cab ou similaire",
        "rate_per_km": 0,
        "rate_per_day": 1200.0,
        "currency": "MAD",
        "specs": {
            "ac": True, "wifi": False, "off_road": True,
            "ratio_pax_per_vehicle": 3,
            "use_cases": ["Erfoud-Merzouga", "Désert", "Pistes Atlas"],
            "luggage_capacity": "Medium",
        },
        "notes": "Pick-up adapté aux pistes sahariennes. Climatisé, sièges confortables. Idéal pour petits groupes.",
    },
    {
        "label": "4×4 Mitsubishi Pajero — Atlas",
        "type": "4wd",
        "capacity_min": 1,
        "capacity_max": 4,
        "brand_models": "Mitsubishi Pajero, Nissan Patrol ou similaire",
        "rate_per_km": 0,
        "rate_per_day": 1400.0,
        "currency": "MAD",
        "specs": {
            "ac": True, "wifi": False, "off_road": True,
            "ratio_pax_per_vehicle": 4,
            "use_cases": ["Haut Atlas", "Todra", "Dades", "Tichka"],
            "luggage_capacity": "Large",
        },
        "notes": "SUV tout-terrain pour les gorges du Dadès, Todra et cols de l'Atlas. Suspension renforcée.",
    },
    {
        "label": "4×4 Mercedes Classe G — VIP",
        "type": "4wd",
        "capacity_min": 1,
        "capacity_max": 4,
        "brand_models": "Mercedes-Benz Classe G 350d ou similaire",
        "rate_per_km": 0,
        "rate_per_day": 3500.0,
        "currency": "MAD",
        "specs": {
            "ac": True, "wifi": True, "off_road": True,
            "ratio_pax_per_vehicle": 4,
            "use_cases": ["VIP", "Désert", "Atlas"],
            "luggage_capacity": "Large",
            "leather_seats": True,
            "premium": True,
        },
        "notes": "4×4 premium pour clientèle VIP. Cuir, climatisation bi-zone, système multimédia. Parfait pour incentive haut de gamme.",
    },
]


if __name__ == "__main__":
    print(f"Activities: {len(ACTIVITIES_CATALOG)} items")
    print(f"Document templates: {len(DOCUMENT_TEMPLATES)} items")
    print(f"4x4 vehicles: {len(VEHICLE_4X4_ADDITIONS)} items")
    for a in ACTIVITIES_CATALOG:
        print(f"  [{a['code']}] {a['name']} — {a['city']} — {a['cost_per_pax']} MAD")
