"""Travel Companion — magic-link tokens for client-facing PWA.

A TravelLink is generated by the agency, sent to the client (email / SMS /
WhatsApp), and grants READ-ONLY access to a trip's program, vouchers, contacts,
weather and live ops status.

No JWT, no password — just a hard-to-guess token in the URL plus optional
PIN (e.g., last 4 digits of passport / phone) for an extra layer.
"""

from datetime import datetime
from typing import Optional
from sqlalchemy import (
    String, Boolean, DateTime, ForeignKey, Integer, Index,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.shared.models import Base, BaseMixin


class TravelLink(Base, BaseMixin):
    __tablename__ = "travel_links"

    company_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("companies.id", ondelete="CASCADE"), index=True,
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"), index=True,
    )
    token: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    pin: Mapped[Optional[str]] = mapped_column(String(8))  # optional 4-8 digit PIN
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime)
    revoked: Mapped[bool] = mapped_column(Boolean, default=False, index=True)

    last_seen_at: Mapped[Optional[datetime]] = mapped_column(DateTime)
    open_count: Mapped[int] = mapped_column(Integer, default=0)
    locale: Mapped[str] = mapped_column(String(10), default="fr")

    __table_args__ = (
        Index("idx_travel_link_project", "project_id"),
    )


class TravelMessage(Base, BaseMixin):
    """Inbound messages from the client through the companion (réclamations, demandes)."""

    __tablename__ = "travel_messages"

    company_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("companies.id", ondelete="CASCADE"), index=True,
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"), index=True,
    )
    travel_link_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("travel_links.id", ondelete="CASCADE"),
    )
    kind: Mapped[str] = mapped_column(String(20), default="message")  # message|complaint|request
    body: Mapped[str] = mapped_column(String(4000))
    handled: Mapped[bool] = mapped_column(Boolean, default=False, index=True)
