"""final_unified_metadata_batch

Revision ID: 84f1bafd0b70
Revises: 0021
Create Date: 2026-05-06 18:13:11.807034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '84f1bafd0b70'
down_revision = '0021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_requests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.drop_index('ix_ai_requests_user_created')
        batch_op.create_index(batch_op.f('ix_ai_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_requests_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('allotments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_allotments_id'), ['id'], unique=False)

    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_id'), ['id'], unique=False)

    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.alter_column('approvers',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_approval_rules_id'), ['id'], unique=False)

    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_approval_steps_id'), ['id'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_articles_id'), ['id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('idx_audit_entity_time')
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_created', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('circuit_remarks', schema=None) as batch_op:
        batch_op.alter_column('is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_circuit_remarks_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circuit_remarks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circuit_remarks_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_companies_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('contract_rates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_contract_rates_id'), ['id'], unique=False)

    with op.batch_alter_table('contract_seasons', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_contract_seasons_id'), ['id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('idx_contract_active_validity')
        batch_op.create_index(batch_op.f('ix_contracts_article_category'), ['article_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_valid_to'), ['valid_to'], unique=False)

    with op.batch_alter_table('crm_accounts', schema=None) as batch_op:
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'agency'"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'MAD'"))
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'bronze'"))
        batch_op.alter_column('lifecycle_stage',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'prospect'"))
        batch_op.alter_column('health_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'50'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index('idx_crm_account_company_name', ['company_id', 'name'], unique=False)
        batch_op.create_index('idx_crm_account_tier', ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_lifecycle_stage'), ['lifecycle_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_primary_email'), ['primary_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_rfm_segment'), ['rfm_segment'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_accounts_tier'), ['tier'], unique=False)

    with op.batch_alter_table('crm_activities', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_crm_activities_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_type'), ['type'], unique=False)

    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_decision_maker',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_crm_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_id'), ['id'], unique=False)

    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'qualification'"))
        batch_op.alter_column('amount_mad',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('probability',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'20'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_index('idx_crm_deal_dmc_stage')
        batch_op.create_index(batch_op.f('ix_crm_deals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_dmc_stage'), ['dmc_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_stage'), ['stage'], unique=False)

    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index('idx_crm_lead_score', ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_extracted_email'), ['extracted_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_status'), ['status'], unique=False)

    with op.batch_alter_table('crm_nurturing_runs', schema=None) as batch_op:
        batch_op.alter_column('current_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'running'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_crm_nurturing_runs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_nurturing_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_nurturing_runs_sequence_id'), ['sequence_id'], unique=False)

    with op.batch_alter_table('crm_nurturing_sequences', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_crm_nurturing_sequences_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_nurturing_sequences_id'), ['id'], unique=False)

    with op.batch_alter_table('crm_tasks', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'normal'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_crm_tasks_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_tasks_owner_user_id'), ['owner_user_id'], unique=False)

    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'operational'"))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'fr'"))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(true)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_document_templates_id'), ['id'], unique=False)

    with op.batch_alter_table('erp_client_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_client_configs_id'), ['id'], unique=False)

    with op.batch_alter_table('erp_push_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_push_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('generated_references', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index('idx_ref_date', ['date_str'], unique=False)
        batch_op.create_index('idx_ref_dept', ['dept_code'], unique=False)
        batch_op.create_index('idx_ref_group', ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_references_id'), ['id'], unique=False)

    with op.batch_alter_table('guide_availabilities', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_guide_availabilities_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_availabilities_id'), ['id'], unique=False)

    with op.batch_alter_table('invoice_counters', schema=None) as batch_op:
        batch_op.alter_column('last_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_invoice_counters_id'), ['id'], unique=False)

    with op.batch_alter_table('invoice_templates', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_invoice_templates_id'), ['id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('deposit_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('deposit_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('balance_due',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('pdf_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('ix_invoices_company_id')
        batch_op.drop_index('ix_invoices_status')
        batch_op.create_index('idx_invoice_number', ['number'], unique=False)
        batch_op.create_index('idx_invoice_project', ['project_id'], unique=False)
        batch_op.create_index('idx_invoice_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_number'), ['number'], unique=True)
        batch_op.create_foreign_key('fk_invoice_template', 'invoice_templates', ['template_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('ix_itineraries_company_id')
        batch_op.create_index('idx_itinerary_project', ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itineraries_id'), ['id'], unique=False)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.alter_column('ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('idx_iday_itinerary_number')
        batch_op.create_index('idx_iday_itinerary', ['itinerary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_days_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_days_itinerary_id'), ['itinerary_id'], unique=False)

    with op.batch_alter_table('itinerary_template_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_template_days_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_template_days_template_id'), ['template_id'], unique=False)

    with op.batch_alter_table('itinerary_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_templates_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_templates_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_templates_id'), ['id'], unique=False)

    with op.batch_alter_table('m365_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_m365_connections_id'), ['id'], unique=False)

    with op.batch_alter_table('m365_linked_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_m365_linked_messages_id'), ['id'], unique=False)

    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_id'), ['id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('ix_notifications_company_id')
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('idx_partner_company_name')
        batch_op.create_index(batch_op.f('ix_partners_id'), ['id'], unique=False)

    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.drop_index('idx_pr_invoice')
        batch_op.drop_index('idx_pr_status')
        batch_op.create_index(batch_op.f('ix_payment_reminders_id'), ['id'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index('idx_permission_module', ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('idx_project_active_created')
        batch_op.drop_index('idx_project_list_covering')
        batch_op.drop_index('ix_projects_status_updated_at')
        batch_op.drop_index('uq_projects_reference')
        batch_op.create_index('idx_project_client', ['client_name'], unique=False)
        batch_op.create_index('idx_project_company_active', ['company_id', 'active'], unique=False)
        batch_op.create_index('idx_project_company_status', ['company_id', 'status', 'active'], unique=False)
        batch_op.create_index('idx_project_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_project_company', 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('proposal_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_proposal_comments_id'), ['id'], unique=False)

    with op.batch_alter_table('proposal_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_proposal_shares_id'), ['id'], unique=False)

    with op.batch_alter_table('quotation_lines', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('is_included',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('idx_qline_quotation_category')
        batch_op.create_index('idx_qline_quotation', ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_lines_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_lines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_lines_quotation_id'), ['quotation_id'], unique=False)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('margin_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('ix_quotations_company_id')
        batch_op.drop_index('ix_quotations_status_created')
        batch_op.create_index('idx_quotation_project', ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_id'), ['id'], unique=False)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('reference_counters', schema=None) as batch_op:
        batch_op.alter_column('last_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index('idx_counter_key', ['dept_code', 'date_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_counters_id'), ['id'], unique=False)

    with op.batch_alter_table('report_data_records', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index('idx_record_source', ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_data_records_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_data_records_id'), ['id'], unique=False)

    with op.batch_alter_table('report_data_sources', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_report_data_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_data_sources_name'), ['name'], unique=False)

    with op.batch_alter_table('report_export_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_report_export_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_export_logs_report_id'), ['report_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('is_template',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index('idx_report_template', ['is_template'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    with op.batch_alter_table('supplier_incidents', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_supplier_incidents_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_incidents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_incidents_partner_id'), ['partner_id'], unique=False)

    with op.batch_alter_table('supplier_score_snapshots', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_supplier_score_snapshots_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_score_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_score_snapshots_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_score_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    with op.batch_alter_table('travel_links', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_travel_links_id'), ['id'], unique=False)

    with op.batch_alter_table('travel_messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_travel_messages_id'), ['id'], unique=False)

    with op.batch_alter_table('user_companies', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_companies_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('ix_users_email_active')
        batch_op.create_index('idx_user_email_active', ['email', 'is_active'], unique=False)
        batch_op.create_index('idx_user_role_id', ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_role_id')
        batch_op.drop_index('idx_user_email_active')
        batch_op.create_index('ix_users_email_active', ['email', 'is_active'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('user_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_companies_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('travel_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_travel_messages_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('travel_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_travel_links_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('supplier_score_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_score_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_supplier_score_snapshots_partner_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_score_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_score_snapshots_company_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('supplier_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_incidents_partner_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_incidents_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_incidents_company_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_project_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_id'))
        batch_op.drop_index('idx_report_template')
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_template',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('report_export_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_export_logs_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_export_logs_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('report_data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_data_sources_name'))
        batch_op.drop_index(batch_op.f('ix_report_data_sources_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('report_data_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_data_records_id'))
        batch_op.drop_index(batch_op.f('ix_report_data_records_data_source_id'))
        batch_op.drop_index('idx_record_source')
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('reference_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_counters_id'))
        batch_op.drop_index('idx_counter_key')
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('last_num',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_index(batch_op.f('ix_quotations_id'))
        batch_op.drop_index('idx_quotation_project')
        batch_op.create_index('ix_quotations_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_quotations_company_id', ['company_id'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('margin_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quotation_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_lines_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_lines_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_lines_category'))
        batch_op.drop_index('idx_qline_quotation')
        batch_op.create_index('idx_qline_quotation_category', ['quotation_id', 'category', 'is_included'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_included',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('proposal_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_shares_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('active')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('proposal_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_comments_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('active')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_reference'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index('idx_project_status')
        batch_op.drop_index('idx_project_company_status')
        batch_op.drop_index('idx_project_company_active')
        batch_op.drop_index('idx_project_client')
        batch_op.create_index('uq_projects_reference', ['reference'], unique=1)
        batch_op.create_index('ix_projects_status_updated_at', ['status', 'updated_at'], unique=False)
        batch_op.create_index('idx_project_list_covering', ['active', 'status', 'updated_at'], unique=False)
        batch_op.create_index('idx_project_active_created', ['active', 'created_at'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_id'))
        batch_op.drop_index('idx_permission_module')
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_reminders_id'))
        batch_op.create_index('idx_pr_status', ['status'], unique=False)
        batch_op.create_index('idx_pr_invoice', ['invoice_id'], unique=False)
        batch_op.drop_column('active')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_id'))
        batch_op.create_index('idx_partner_company_name', ['company_id', 'name'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_project_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.create_index('ix_notifications_user_read', ['recipient_id', 'is_read'], unique=False)
        batch_op.create_index('ix_notifications_company_id', ['company_id'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_id'))
        batch_op.drop_index(batch_op.f('ix_media_assets_company_id'))
        batch_op.drop_index(batch_op.f('ix_media_assets_city'))

    with op.batch_alter_table('m365_linked_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_m365_linked_messages_id'))
        batch_op.drop_column('active')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('m365_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_m365_connections_id'))
        batch_op.drop_column('active')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('itinerary_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_templates_id'))
        batch_op.drop_index(batch_op.f('ix_itinerary_templates_destination'))
        batch_op.drop_index(batch_op.f('ix_itinerary_templates_company_id'))

    with op.batch_alter_table('itinerary_template_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_template_days_template_id'))
        batch_op.drop_index(batch_op.f('ix_itinerary_template_days_id'))

    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_days_itinerary_id'))
        batch_op.drop_index(batch_op.f('ix_itinerary_days_id'))
        batch_op.drop_index('idx_iday_itinerary')
        batch_op.create_index('idx_iday_itinerary_number', ['itinerary_id', 'day_number'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_index(batch_op.f('ix_itineraries_id'))
        batch_op.drop_index('idx_itinerary_project')
        batch_op.create_index('ix_itineraries_company_id', ['company_id'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))
        batch_op.drop_index('idx_invoice_status')
        batch_op.drop_index('idx_invoice_project')
        batch_op.drop_index('idx_invoice_number')
        batch_op.create_index('ix_invoices_status', ['status'], unique=False)
        batch_op.create_index('ix_invoices_company_id', ['company_id'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('pdf_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('balance_due',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('deposit_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('deposit_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('invoice_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_templates_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('invoice_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_counters_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('last_num',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('guide_availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_availabilities_id'))
        batch_op.drop_index(batch_op.f('ix_guide_availabilities_guide_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('generated_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_references_id'))
        batch_op.drop_index('idx_ref_group')
        batch_op.drop_index('idx_ref_dept')
        batch_op.drop_index('idx_ref_date')
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('erp_push_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_push_logs_id'))

    with op.batch_alter_table('erp_client_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_client_configs_id'))

    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_templates_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(true)'))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'fr'"))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'operational'"))
        batch_op.drop_column('created_by')

    with op.batch_alter_table('crm_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_tasks_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_company_id'))
        batch_op.drop_index(batch_op.f('ix_crm_tasks_account_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'normal'"))

    with op.batch_alter_table('crm_nurturing_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_nurturing_sequences_id'))
        batch_op.drop_index(batch_op.f('ix_crm_nurturing_sequences_company_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('crm_nurturing_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_nurturing_runs_sequence_id'))
        batch_op.drop_index(batch_op.f('ix_crm_nurturing_runs_id'))
        batch_op.drop_index(batch_op.f('ix_crm_nurturing_runs_account_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'running'"))
        batch_op.alter_column('current_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_leads_status'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_source'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_score'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_received_at'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_id'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_extracted_email'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_company_id'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_assigned_to_user_id'))
        batch_op.drop_index('idx_crm_lead_score')
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_deals_stage'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_project_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_dmc_stage'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_company_id'))
        batch_op.create_index('idx_crm_deal_dmc_stage', ['dmc_stage'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('probability',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'20'"))
        batch_op.alter_column('amount_mad',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'qualification'"))

    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_company_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_decision_maker',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('crm_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_activities_type'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_company_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_account_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('crm_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_accounts_tier'))
        batch_op.drop_index(batch_op.f('ix_crm_accounts_rfm_segment'))
        batch_op.drop_index(batch_op.f('ix_crm_accounts_primary_email'))
        batch_op.drop_index(batch_op.f('ix_crm_accounts_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_crm_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_crm_accounts_lifecycle_stage'))
        batch_op.drop_index(batch_op.f('ix_crm_accounts_id'))
        batch_op.drop_index(batch_op.f('ix_crm_accounts_country'))
        batch_op.drop_index(batch_op.f('ix_crm_accounts_code'))
        batch_op.drop_index(batch_op.f('ix_crm_accounts_account_type'))
        batch_op.drop_index('idx_crm_account_tier')
        batch_op.drop_index('idx_crm_account_company_name')
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('health_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'50'"))
        batch_op.alter_column('lifecycle_stage',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'prospect'"))
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'bronze'"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'MAD'"))
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'agency'"))

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_valid_to'))
        batch_op.drop_index(batch_op.f('ix_contracts_valid_from'))
        batch_op.drop_index(batch_op.f('ix_contracts_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_code'))
        batch_op.drop_index(batch_op.f('ix_contracts_article_category'))
        batch_op.create_index('idx_contract_active_validity', ['status', 'valid_from', 'valid_to'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('contract_seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_seasons_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('contract_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_rates_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_is_active'))
        batch_op.drop_index(batch_op.f('ix_companies_id'))
        batch_op.drop_index(batch_op.f('ix_companies_code'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('circuit_remarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circuit_remarks_project_id'))
        batch_op.drop_index(batch_op.f('ix_circuit_remarks_id'))
        batch_op.drop_index(batch_op.f('ix_circuit_remarks_guide_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_entity')
        batch_op.drop_index('idx_audit_created')
        batch_op.drop_index('idx_audit_action')
        batch_op.create_index('idx_audit_entity_time', ['entity_id', 'created_at'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_steps_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_rules_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('approvers',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('allotments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allotments_id'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('ai_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_requests_project_id'))
        batch_op.create_index('ix_ai_requests_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
