"""Rich seed data for the Catalogue Premium.

~30 hôtels · ~25 restaurants · ~20 activités · ~15 guides — données réelles
des partenaires marocains type S'TOURS, avec adresses, photos Unsplash,
spécialités, tarifs PAX, langues, étoiles, et notes internes.
"""
from datetime import date

# ─── HÔTELS ──────────────────────────────────────────────────────────────────
HOTELS = [
    # Marrakech (8)
    {"slug":"royal-mansour-mk","name":"Royal Mansour Marrakech","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Rue Abou Abbas El Sebti","phone":"+212 5 29 80 80 80","email":"reservations@royalmansour.ma",
     "website":"https://www.royalmansour.com","stars":5,"category":"5* Palace","rating":4.95,
     "unit_cost":4800,"currency":"MAD","cost_unit":"per_night_dbl","single_supplement":1800,
     "specs":{"room_types":["Riad 1 ch","Riad 2 ch","Riad 3 ch"],"amenities":["spa","piscine","hammam","restaurant gastro","conciergerie"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True,"season_high":"Oct-Mai"},
     "short_description":"Palace ultra-luxe propriété royale, riads privés avec patios.",
     "cover_url":"https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=900",
     "tags":["luxe","palace","prestige","spa"],
     "internal_note":"Partenaire stratégique. Commission directe 12 %. Clients VVIP uniquement (Voyageurs du Monde, Audley).",
     "partner_since":date(2018,3,1),"is_preferred":True,"is_exclusive":False},
    {"slug":"mamounia","name":"La Mamounia","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Avenue Bab Jdid","phone":"+212 5 24 38 86 00","email":"reservation@mamounia.com",
     "website":"https://www.mamounia.com","stars":5,"category":"5* Palace","rating":4.93,
     "unit_cost":3900,"currency":"MAD","cost_unit":"per_night_dbl","single_supplement":1500,
     "specs":{"room_types":["Deluxe","Junior Suite","Riad Suite","Mamounia Suite"],
              "amenities":["jardins historiques 8ha","spa Mamounia","4 restos","piscine olympique","cinéma"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True,"season_high":"Oct-Mai"},
     "short_description":"Palace iconique 1923 avec jardins, classé monde.",
     "cover_url":"https://images.unsplash.com/photo-1582719508461-905c673771fd?w=900",
     "tags":["palace","historique","jardins","gastronomique"],
     "internal_note":"Top réceptif Marrakech. Allotment confirmé 4 ch nov-mars. Référent: Karim Nadir.",
     "partner_since":date(2015,1,15),"is_preferred":True},
    {"slug":"selman-mk","name":"Selman Marrakech","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Km 5 Route d'Amizmiz","phone":"+212 5 24 45 96 00","stars":5,"category":"5* Resort",
     "rating":4.7,"unit_cost":2400,"currency":"MAD","cost_unit":"per_night_dbl","single_supplement":900,
     "specs":{"room_types":["Deluxe","Pavillon","Riad"],
              "amenities":["écuries pur-sang arabes","spa Chenot","piscine 80m","resto Le Selman"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Resort équestre signature Selman, écuries de pur-sang arabes visitables.",
     "cover_url":"https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=900",
     "tags":["resort","spa","équestre","famille"],
     "internal_note":"Excellent pour groupes 25-50 PAX. Spa Chenot ouvert depuis 2022.",
     "partner_since":date(2017,6,1)},
    {"slug":"mandarin-mk","name":"Mandarin Oriental Marrakech","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Route Golf Royal","phone":"+212 5 24 29 88 88","stars":5,"category":"5* Palace",
     "rating":4.88,"unit_cost":4200,"currency":"MAD","cost_unit":"per_night_dbl","single_supplement":1600,
     "specs":{"room_types":["Villa Pool","Mandarin Suite","Présidentielle"],
              "amenities":["villas privées","piscines individuelles","spa 1500m²","Olivier by Pierre Gagnaire"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"100 % villas avec piscine privée, gastronomie 2-étoiles Pierre Gagnaire.",
     "cover_url":"https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=900",
     "tags":["luxe","villa","gastronomique","spa"],
     "internal_note":"Best pour couples HNW. Pierre Gagnaire = +30% de l'addition F&B.",
     "partner_since":date(2019,2,10),"is_preferred":True},
    {"slug":"riad-fes-marrakech","name":"Riad Joya","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Derb El Hammam, Médina","phone":"+212 5 24 39 18 03","stars":5,"category":"Riad luxe",
     "rating":4.85,"unit_cost":1900,"currency":"MAD","cost_unit":"per_night_dbl","single_supplement":700,
     "specs":{"room_types":["Suite","Master Suite"],"amenities":["6 suites privatisables","hammam","cuisine privée","majordome"],
              "breakfast_included":True,"pool":False,"spa":True,"has_restaurant":True},
     "short_description":"Riad 6 suites privatisable en exclusivité, médina classée.",
     "cover_url":"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=900",
     "tags":["riad","intimiste","exclusif","médina"],
     "internal_note":"Privatisation totale 6 ch = 11 400 MAD/nuit. Idéal honeymoon haut de gamme.",
     "partner_since":date(2020,9,1),"is_exclusive":True},
    {"slug":"oberoi-mk","name":"The Oberoi Marrakech","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Route d'Ouarzazate Km 2","phone":"+212 5 24 04 55 00","stars":5,"category":"5* Resort",
     "rating":4.91,"unit_cost":3600,"currency":"MAD","cost_unit":"per_night_dbl","single_supplement":1300,
     "specs":{"room_types":["Premier","Luxury Suite","Royal Villa"],
              "amenities":["28ha jardins","piscine 80m","spa Oberoi","resto Mughal"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Resort signature Oberoi, jardins andalous et piscine olympique.",
     "cover_url":"https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900",
     "tags":["luxe","resort","jardins","calme"],
     "internal_note":"Très demandé clients américains. 30 ch allotment groupes mariages.",
     "partner_since":date(2021,4,15),"is_preferred":True},
    {"slug":"farnatchi","name":"Riad Farnatchi","city":"Marrakech","region":"Marrakech-Safi",
     "address":"2 Derb el Farnatchi","phone":"+212 5 24 38 49 10","stars":5,"category":"Riad luxe",
     "rating":4.8,"unit_cost":1700,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Suite","Suite Junior"],"amenities":["10 suites","hammam","piscine","restaurant"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Riad bijou 10 suites en pleine médina, design contemporain marocain.",
     "cover_url":"https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=900",
     "tags":["riad","design","médina","romantique"],
     "internal_note":"Service impeccable. Chef privatif disponible (1500 MAD/repas).",
     "partner_since":date(2019,11,1)},
    {"slug":"kasbah-tamadot","name":"Kasbah Tamadot","city":"Asni","region":"Marrakech-Safi",
     "address":"Route Imlil, Asni","phone":"+212 5 24 36 82 00","stars":5,"category":"Kasbah luxe",
     "rating":4.92,"unit_cost":3200,"currency":"MAD","cost_unit":"per_night_dbl","single_supplement":1200,
     "specs":{"room_types":["Master Suite","Berber Tent","Kasbah Suite"],
              "amenities":["vue Atlas","tentes berbères","piscine chauffée","spa"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Kasbah Richard Branson au pied du Toubkal, mix luxe & authentique.",
     "cover_url":"https://images.unsplash.com/photo-1570213489059-0aac6626cade?w=900",
     "tags":["kasbah","atlas","exclusif","montagne"],
     "internal_note":"45 min de Marrakech. Tarifs négociés Virgin pour groupes Audley.",
     "partner_since":date(2018,7,1),"is_exclusive":True},

    # Fès (4)
    {"slug":"palais-faraj","name":"Palais Faraj","city":"Fès","region":"Fès-Meknès",
     "address":"Quartier Ziat, Bab Ziat","phone":"+212 5 35 63 53 56","stars":5,"category":"5*",
     "rating":4.7,"unit_cost":1450,"currency":"MAD","cost_unit":"per_night_dbl","single_supplement":500,
     "specs":{"room_types":["Deluxe","Suite Junior","Suite Royale"],
              "amenities":["vue médina","spa Hammam","piscine rooftop","resto L'Amandier"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Palais 19e siècle restauré dominant la médina classée UNESCO.",
     "cover_url":"https://images.unsplash.com/photo-1539020140153-e8c237112e1d?w=900",
     "tags":["palais","médina","historique","unesco"],
     "internal_note":"Best vue de Fès. Resto rooftop top pour gala 30 PAX max.",
     "partner_since":date(2016,5,1),"is_preferred":True},
    {"slug":"riad-fes","name":"Riad Fès Relais & Châteaux","city":"Fès","region":"Fès-Meknès",
     "address":"5 Derb Ben Slimane Zerbtana","phone":"+212 5 35 94 76 10","stars":5,"category":"Riad luxe",
     "rating":4.8,"unit_cost":1850,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Riad Suite","Garden Suite"],
              "amenities":["3 piscines","spa","resto étoilé","cours cuisine"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Relais & Châteaux dans la médina, 2 patios andalous.",
     "cover_url":"https://images.unsplash.com/photo-1631049035326-57414e7739c0?w=900",
     "tags":["riad","relais-châteaux","gastronomique","médina"],
     "internal_note":"Cours cuisine signature 850 MAD/PAX, à booker 48h avance.",
     "partner_since":date(2017,8,15),"is_preferred":True},
    {"slug":"jnan-palace-fes","name":"Jnan Palace Fès","city":"Fès","region":"Fès-Meknès",
     "address":"Avenue Ahmed Chaouki","phone":"+212 5 35 65 39 65","stars":5,"category":"5* Resort",
     "rating":4.5,"unit_cost":1100,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Deluxe","Suite Junior","Suite Royale"],
              "amenities":["220 chambres","jardins andalous 7ha","2 piscines","centre conf"],
              "breakfast_included":True,"pool":True,"spa":False,"has_restaurant":True},
     "short_description":"Resort grande capacité idéal groupes / MICE 200+ PAX.",
     "cover_url":"https://images.unsplash.com/photo-1592229505726-ca121723b8ef?w=900",
     "tags":["resort","mice","groupes","jardins"],
     "internal_note":"Ville nouvelle (10 min médina). Fortes capacités banquet 400 PAX.",
     "partner_since":date(2014,3,1)},
    {"slug":"sahrai","name":"Hotel Sahrai","city":"Fès","region":"Fès-Meknès",
     "address":"Bab Lghoul Dhar El Mehraz","phone":"+212 5 35 94 03 32","stars":5,"category":"5* Design",
     "rating":4.65,"unit_cost":1600,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Deluxe","Junior Suite","Penthouse"],
              "amenities":["design Christophe Pillet","piscine ext","Givenchy spa","rooftop bar"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Design hôtel contemporain avec vue panoramique sur la médina.",
     "cover_url":"https://images.unsplash.com/photo-1455587734955-081b22074882?w=900",
     "tags":["design","contemporain","panoramique","spa"],
     "internal_note":"Givenchy spa = vraiment haut de gamme. Bar rooftop top sunset.",
     "partner_since":date(2020,5,1)},

    # Casablanca (3)
    {"slug":"four-seasons-casa","name":"Four Seasons Hotel Casablanca","city":"Casablanca","region":"Casablanca-Settat",
     "address":"Boulevard de la Corniche","phone":"+212 5 29 07 30 30","stars":5,"category":"5*",
     "rating":4.85,"unit_cost":2400,"currency":"MAD","cost_unit":"per_night_dbl","single_supplement":900,
     "specs":{"room_types":["Premier","Junior Suite","Suite Atlantique"],
              "amenities":["vue océan","spa","piscine ext","Bleu by FS"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"FS face à l'océan corniche Ain Diab, 5* business + loisir.",
     "cover_url":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=900",
     "tags":["business","océan","ville","gastronomique"],
     "internal_note":"Standard FS impeccable. Negociation possible pour MICE 50+.",
     "partner_since":date(2017,9,1),"is_preferred":True},
    {"slug":"sofitel-casa","name":"Sofitel Casablanca Tour Blanche","city":"Casablanca","region":"Casablanca-Settat",
     "address":"Rue Sidi Belyout","phone":"+212 5 22 45 62 00","stars":5,"category":"5*",
     "rating":4.55,"unit_cost":1800,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Deluxe","Suite"],"amenities":["centre ville","spa","resto Brasserie","piscine intérieure"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"5* business district, idéal arrivée/départ.",
     "cover_url":"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900",
     "tags":["business","centre-ville","corporate"],
     "internal_note":"Souvent J1/J11 d'un circuit. Tarif corporate négocié avec ID Travel.",
     "partner_since":date(2015,1,1)},
    {"slug":"hyatt-casa","name":"Hyatt Regency Casablanca","city":"Casablanca","region":"Casablanca-Settat",
     "address":"Place des Nations Unies","phone":"+212 5 22 43 12 34","stars":5,"category":"5*",
     "rating":4.4,"unit_cost":1500,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Standard","Club","Suite"],"amenities":["centre ville","piscine","fitness","Bar Rick's reference"],
              "breakfast_included":False,"pool":True,"spa":False,"has_restaurant":True},
     "short_description":"Hyatt centre Casa, 4 restaurants dont le Rick's Bar.",
     "cover_url":"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=900",
     "tags":["business","ville","central"],
     "internal_note":"Fonctionnel, pas wow. Bon rapport qualité-prix groupes.",
     "partner_since":date(2014,11,1)},

    # Rabat (2)
    {"slug":"sofitel-rabat","name":"Sofitel Rabat Jardin des Roses","city":"Rabat","region":"Rabat-Salé-Kénitra",
     "address":"BP 450 Souissi","phone":"+212 5 37 67 56 56","stars":5,"category":"5*",
     "rating":4.6,"unit_cost":1650,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Luxe","Suite Junior","Suite Présidentielle"],
              "amenities":["jardins 17ha","spa Sofitel","2 piscines","golf à proximité"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"5* Accor avec jardins andalous, hors centre dans quartier diplomatique.",
     "cover_url":"https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=900",
     "tags":["jardins","diplomatique","spa"],
     "internal_note":"Best Rabat. Spa Sofitel hammam-couples 1200 MAD/2 PAX.",
     "partner_since":date(2016,3,1),"is_preferred":True},
    {"slug":"villa-mandarine","name":"La Villa Mandarine","city":"Rabat","region":"Rabat-Salé-Kénitra",
     "address":"19 Rue Ouled Bousbaa Souissi","phone":"+212 5 37 75 20 77","stars":4,"category":"Boutique 4*",
     "rating":4.7,"unit_cost":950,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Confort","Suite Familiale"],
              "amenities":["jardin orangerie","piscine","resto bistronomique","30 ch"],
              "breakfast_included":True,"pool":True,"spa":False,"has_restaurant":True},
     "short_description":"Boutique-hôtel familial dans une ancienne villa diplomatique.",
     "cover_url":"https://images.unsplash.com/photo-1551776235-dde6d482980b?w=900",
     "tags":["boutique","familial","jardin"],
     "internal_note":"Service plus chaleureux que Sofitel. Resto bistronomique.",
     "partner_since":date(2018,10,1)},

    # Sahara / désert (3)
    {"slug":"sahara-luxe-camp","name":"Sahara Luxury Camp","city":"Merzouga","region":"Drâa-Tafilalet",
     "address":"Erg Chebbi, Merzouga","phone":"+212 6 61 21 11 11","stars":5,"category":"Camp luxe",
     "rating":4.85,"unit_cost":1800,"currency":"MAD","cost_unit":"per_pax",
     "specs":{"room_types":["Tente luxe","Suite Tente"],
              "amenities":["dunes Erg Chebbi","SDB privée","resto bivouac","gala berbère"],
              "breakfast_included":True,"pool":False,"spa":False,"has_restaurant":True},
     "short_description":"Camp luxe 5* parmi les dunes de Merzouga, expérience gala berbère.",
     "cover_url":"https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900",
     "tags":["désert","sahara","authentique","aventure"],
     "internal_note":"Inclut chameau aller/retour + gala. Allotment 8 tentes = 16 PAX.",
     "partner_since":date(2017,2,1),"is_preferred":True,"is_exclusive":True},
    {"slug":"chigaga-desert-camp","name":"Camp Erg Chigaga","city":"M'Hamid","region":"Drâa-Tafilalet",
     "address":"Erg Chigaga, M'Hamid","phone":"+212 6 62 88 87 87","stars":5,"category":"Camp luxe",
     "rating":4.7,"unit_cost":1500,"currency":"MAD","cost_unit":"per_pax",
     "specs":{"room_types":["Tente Bédouine","Suite Royale"],
              "amenities":["dunes Chigaga","piscine","yoga sunrise","sandboard"],
              "breakfast_included":True,"pool":True,"spa":False,"has_restaurant":True},
     "short_description":"Camp Sud-Sud Maroc plus reculé, idéal pour vrais aventuriers.",
     "cover_url":"https://images.unsplash.com/photo-1473165089983-8e9c84d20f4f?w=900",
     "tags":["désert","aventure","reculé","authentique"],
     "internal_note":"Plus authentique que Merzouga. 2j 4x4 transfert depuis Ouarzazate.",
     "partner_since":date(2019,9,1)},
    {"slug":"berbere-palace-zagora","name":"Berbère Palace","city":"Ouarzazate","region":"Drâa-Tafilalet",
     "address":"Quartier Mansour Eddahbi","phone":"+212 5 24 88 31 05","stars":5,"category":"5*",
     "rating":4.4,"unit_cost":1100,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Standard","Suite","Riad"],"amenities":["piscine","spa","jardins","resto pré-désert"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Hôtel kasbah Ouarzazate, base idéale avant/après désert.",
     "cover_url":"https://images.unsplash.com/photo-1582719508461-905c673771fd?w=900",
     "tags":["kasbah","ouarzazate","groupes"],
     "internal_note":"Standard pour étape avant/après Merzouga. Piscine très demandée juin-août.",
     "partner_since":date(2014,6,15)},

    # Essaouira / Côte (2)
    {"slug":"heure-bleue","name":"Heure Bleue Palais","city":"Essaouira","region":"Marrakech-Safi",
     "address":"2 Rue Ibn Batouta","phone":"+212 5 24 78 34 34","stars":5,"category":"5*",
     "rating":4.75,"unit_cost":1350,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Suite","Riad Suite"],"amenities":["rooftop océan","piscine intérieure","spa","cinéma"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Palais Relais & Châteaux médina d'Essaouira, vue océan.",
     "cover_url":"https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=900",
     "tags":["palais","océan","relais-châteaux","médina"],
     "internal_note":"Salle cinéma privée incluse. Top pour escapades couples.",
     "partner_since":date(2018,4,1),"is_preferred":True},
    {"slug":"sofitel-essaouira","name":"Sofitel Essaouira Mogador Golf & Spa","city":"Essaouira","region":"Marrakech-Safi",
     "address":"Domaine Mogador","phone":"+212 5 24 47 94 00","stars":5,"category":"5* Resort",
     "rating":4.55,"unit_cost":1450,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Luxe","Suite"],"amenities":["golf 18 trous","spa","piscine","plage privée"],
              "breakfast_included":True,"pool":True,"spa":True,"has_restaurant":True},
     "short_description":"Resort golf en bord de plage, idéal couples & golfeurs.",
     "cover_url":"https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=900",
     "tags":["golf","plage","spa","resort"],
     "internal_note":"Greenfee golf 800 MAD/PAX. Plage venteuse mais super pour kitesurf.",
     "partner_since":date(2016,7,1)},

    # Chefchaouen / Nord (2)
    {"slug":"lina-ryad","name":"Lina Ryad & Spa","city":"Chefchaouen","region":"Tanger-Tétouan-Al Hoceima",
     "address":"Quartier Hauma","phone":"+212 5 39 98 71 12","stars":4,"category":"Boutique 4*",
     "rating":4.6,"unit_cost":890,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Standard","Suite"],"amenities":["spa","hammam","rooftop bleu","resto"],
              "breakfast_included":True,"pool":False,"spa":True,"has_restaurant":True},
     "short_description":"Boutique riad bleu emblématique, plein cœur de la médina.",
     "cover_url":"https://images.unsplash.com/photo-1597212720158-e21091b5beb3?w=900",
     "tags":["boutique","médina","authentique","photogénique"],
     "internal_note":"Idéal escale 1 nuit après Fès. Photos médina top.",
     "partner_since":date(2019,4,1)},
    {"slug":"casa-hassan","name":"Casa Hassan","city":"Chefchaouen","region":"Tanger-Tétouan-Al Hoceima",
     "address":"Rue Targui 22","phone":"+212 5 39 98 61 53","stars":3,"category":"Maison hôte 3*",
     "rating":4.4,"unit_cost":620,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Standard"],"amenities":["resto traditionnel","accueil familial","13 ch"],
              "breakfast_included":True,"pool":False,"spa":False,"has_restaurant":True},
     "short_description":"Maison d'hôte historique de Chefchaouen, accueil familial.",
     "cover_url":"https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=900",
     "tags":["maison-hôte","familial","budget"],
     "internal_note":"Bon plan budget. Resto rooftop avec vue chaouenne typique.",
     "partner_since":date(2015,3,1)},

    # Tanger (2)
    {"slug":"villa-josephine","name":"Villa Joséphine","city":"Tanger","region":"Tanger-Tétouan-Al Hoceima",
     "address":"231 Rue Sidi Mesmoudi","phone":"+212 5 39 33 45 70","stars":4,"category":"Boutique 5*",
     "rating":4.78,"unit_cost":1450,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Suite Vue Mer","Suite Junior"],
              "amenities":["10 suites","jardins","piscine","panorama Détroit"],
              "breakfast_included":True,"pool":True,"spa":False,"has_restaurant":True},
     "short_description":"Villa coloniale boutique sur la Vieille Montagne, vue Détroit.",
     "cover_url":"https://images.unsplash.com/photo-1582719508461-905c673771fd?w=900",
     "tags":["boutique","vue-mer","intimiste"],
     "internal_note":"Top pour groupes 10-15 PAX privatisé. Vue Espagne sublime.",
     "partner_since":date(2020,6,1)},
    {"slug":"hilton-tanger","name":"Hilton Garden Inn Tanger","city":"Tanger","region":"Tanger-Tétouan-Al Hoceima",
     "address":"Avenue Mohammed VI","phone":"+212 5 39 39 78 00","stars":4,"category":"4*",
     "rating":4.3,"unit_cost":850,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Standard","Family"],"amenities":["bord de mer","piscine","fitness","Bar"],
              "breakfast_included":False,"pool":True,"spa":False,"has_restaurant":True},
     "short_description":"Hilton standard bord de mer, fonctionnel.",
     "cover_url":"https://images.unsplash.com/photo-1455587734955-081b22074882?w=900",
     "tags":["chaîne","fonctionnel","bord-mer"],
     "internal_note":"Plan B Tanger si Joséphine complet. OK pour groupes 50 PAX.",
     "partner_since":date(2017,9,1)},

    # Atlas / Imlil (1)
    {"slug":"riad-toubkal","name":"Kasbah du Toubkal","city":"Imlil","region":"Marrakech-Safi",
     "address":"Imlil, Asni","phone":"+212 5 24 48 56 11","stars":4,"category":"Kasbah écotourisme",
     "rating":4.85,"unit_cost":1200,"currency":"MAD","cost_unit":"per_pax",
     "specs":{"room_types":["Tente Berbère","Chambre","Suite Imlil"],
              "amenities":["panorama Toubkal","randos guidées","cours hammam","village"],
              "breakfast_included":True,"pool":False,"spa":True,"has_restaurant":True},
     "short_description":"Kasbah écotourisme partagée avec village Imlil, idéal trek Toubkal.",
     "cover_url":"https://images.unsplash.com/photo-1604608672516-f1b9b1d11b04?w=900",
     "tags":["montagne","écotourisme","trek","authentique"],
     "internal_note":"Modèle écotouristique exemplaire (5% CA reversé village).",
     "partner_since":date(2018,8,1),"is_preferred":True},

    # Volubilis / Meknès (1)
    {"slug":"riad-yacout","name":"Riad Yacout","city":"Meknès","region":"Fès-Meknès",
     "address":"5 Derb Bensbâa","phone":"+212 5 35 53 28 11","stars":4,"category":"Riad",
     "rating":4.5,"unit_cost":700,"currency":"MAD","cost_unit":"per_night_dbl",
     "specs":{"room_types":["Standard","Suite"],"amenities":["patio","resto","13 ch","hammam"],
              "breakfast_included":True,"pool":False,"spa":True,"has_restaurant":True},
     "short_description":"Riad médina Meknès, étape Volubilis-Moulay Idriss.",
     "cover_url":"https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=900",
     "tags":["riad","médina","étape"],
     "internal_note":"Étape pratique Meknès-Volubilis. Jamais en first choice.",
     "partner_since":date(2016,11,1)},
]


# ─── RESTAURANTS ──────────────────────────────────────────────────────────────
RESTAURANTS = [
    # Marrakech (8)
    {"slug":"namaskar-palace","name":"Namaskar Palace","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Route de Bab Atlas, Annakhil","phone":"+212 5 24 36 81 00","email":"reservation@namaskar-palace.com",
     "category":"gastronomique","rating":4.7,
     "unit_cost":750,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":120,
     "specs":{"cuisine":"Indo-marocaine signature","ambiance":"Palais romantique","has_terrace":True,
              "dress_code":"smart-casual","dietary":["vegetarian","halal","vegan-on-request"],
              "signature_dishes":["Tandoor d'agneau","Tagine de homard","Curry royal"]},
     "short_description":"Cadre palace, fusion indo-marocaine raffinée, top dîners VVIP.",
     "cover_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900",
     "tags":["palace","gastronomique","signature","romantique"],
     "internal_note":"Notre #1 Marrakech pour dîners gastronomiques 6-30 PAX. Réservation 72h.",
     "partner_since":date(2017,6,1),"is_preferred":True},
    {"slug":"grand-cafe-poste","name":"Le Grand Café de la Poste","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Boulevard El Mansour Eddahbi","phone":"+212 5 24 43 30 38","category":"brasserie",
     "rating":4.5,"unit_cost":380,"currency":"MAD","cost_unit":"per_pax","min_pax":1,"max_pax":80,
     "specs":{"cuisine":"Brasserie française","ambiance":"Coloniale 1920s","has_terrace":True,
              "dress_code":"casual","dietary":["vegetarian"],
              "signature_dishes":["Steak frites","Tartare","Cheesecake maison"]},
     "short_description":"Brasserie coloniale icône de Guéliz, ambiance années 20.",
     "cover_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900",
     "tags":["brasserie","coloniale","guéliz"],
     "internal_note":"Lunch idéal après visite Majorelle. Excellent pour groupes 30 PAX.",
     "partner_since":date(2015,2,1)},
    {"slug":"chez-ali","name":"Chez Ali Fantasia","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Domaine de la Palmeraie","phone":"+212 5 24 30 77 30","category":"gala-spectacle",
     "rating":4.3,"unit_cost":590,"currency":"MAD","cost_unit":"per_pax","min_pax":20,"max_pax":600,
     "specs":{"cuisine":"Marocaine traditionnelle (méchoui, tagines)","ambiance":"Caïdal + spectacle Fantasia",
              "has_terrace":True,"dress_code":"folklorique encouragé","dietary":["halal"],
              "signature_dishes":["Méchoui complet","Tagines individuels","Fantasia équestre"]},
     "short_description":"Dîner-spectacle palmeraie : méchoui + Fantasia équestre + danseurs.",
     "cover_url":"https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=900",
     "tags":["spectacle","groupes","famille","folklorique"],
     "internal_note":"Jusqu'à 600 PAX. Touristique mais redoutable pour groupes 50+.",
     "partner_since":date(2014,5,1)},
    {"slug":"el-fenn-rooftop","name":"El Fenn Rooftop","city":"Marrakech","region":"Marrakech-Safi",
     "address":"2 Derb Moullay Abdullah Ben Hezzian","phone":"+212 5 24 44 12 10",
     "category":"rooftop","rating":4.7,"unit_cost":420,"currency":"MAD","cost_unit":"per_pax",
     "min_pax":1,"max_pax":50,
     "specs":{"cuisine":"Méditerranéenne","ambiance":"Rooftop chic boho","has_terrace":True,
              "dress_code":"smart-casual","dietary":["vegetarian","vegan"],
              "signature_dishes":["Burrata","Filet de poisson grillé","Tarte au citron"]},
     "short_description":"Rooftop de l'iconic El Fenn, vue Atlas et Koutoubia.",
     "cover_url":"https://images.unsplash.com/photo-1552566626-52f8b828add9?w=900",
     "tags":["rooftop","branché","sunset","mediterranéen"],
     "internal_note":"Best sunset Marrakech. Réservation 48h obligatoire.",
     "partner_since":date(2018,9,1),"is_preferred":True},
    {"slug":"dar-yacout","name":"Dar Yacout","city":"Marrakech","region":"Marrakech-Safi",
     "address":"79 Sidi Ahmed Soussi","phone":"+212 5 24 38 29 29","category":"traditionnel",
     "rating":4.6,"unit_cost":680,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":80,
     "specs":{"cuisine":"Marocaine raffinée","ambiance":"Riad palatial","has_terrace":True,
              "dress_code":"smart-casual","dietary":["halal","vegetarian"],
              "signature_dishes":["Pastilla pigeon","Tagines confits","Cornes de gazelle"]},
     "short_description":"Diffa marocaine 7 services dans riad palatial, expérience iconique.",
     "cover_url":"https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=900",
     "tags":["traditionnel","palatial","gastronomique"],
     "internal_note":"Diffa 7 services à 680 MAD/PAX. Spectacle musique gnawa inclus.",
     "partner_since":date(2016,4,1)},
    {"slug":"comptoir-darna","name":"Comptoir Darna","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Avenue Echouhada","phone":"+212 5 24 43 77 02","category":"diner-spectacle",
     "rating":4.4,"unit_cost":480,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":120,
     "specs":{"cuisine":"Méditerranéenne fusion","ambiance":"Lounge + danseuses orientales 22h",
              "has_terrace":True,"dress_code":"chic","dietary":["vegetarian"],
              "signature_dishes":["Carpaccio","Côte de bœuf","Soufflé chocolat"]},
     "short_description":"Dîner-spectacle danseuses orientales 22h, ambiance lounge.",
     "cover_url":"https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900",
     "tags":["lounge","spectacle","fusion","branché"],
     "internal_note":"Spectacle 22h tous les soirs. Bonne alternative à Chez Ali pour 30 PAX max.",
     "partner_since":date(2015,11,1)},
    {"slug":"nomad","name":"Nomad","city":"Marrakech","region":"Marrakech-Safi",
     "address":"1 Derb Aarjane, Médina","phone":"+212 5 24 38 16 09","category":"contemporain",
     "rating":4.65,"unit_cost":350,"currency":"MAD","cost_unit":"per_pax","min_pax":1,"max_pax":40,
     "specs":{"cuisine":"Marocaine moderne","ambiance":"Rooftop minimaliste","has_terrace":True,
              "dress_code":"casual","dietary":["vegetarian","vegan","gluten-free"],
              "signature_dishes":["Calamar grillé harissa","Burger berbère","Pavlova safran"]},
     "short_description":"Cuisine marocaine revisitée, rooftop intimiste sur la place des épices.",
     "cover_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900",
     "tags":["rooftop","moderne","médina","branché"],
     "internal_note":"Capacité limitée — top pour FIT 2-4 PAX. Bookings 24h.",
     "partner_since":date(2019,3,1)},
    {"slug":"bbq-kasbah-agafay","name":"BBQ Berbère Agafay","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Désert d'Agafay, 30 km Marrakech","phone":"+212 6 61 33 22 11","category":"experience",
     "rating":4.55,"unit_cost":380,"currency":"MAD","cost_unit":"per_pax","min_pax":10,"max_pax":80,
     "specs":{"cuisine":"BBQ berbère + tagines","ambiance":"Tentes berbères au coucher du soleil",
              "has_terrace":True,"dress_code":"casual chaud","dietary":["halal"],
              "signature_dishes":["Brochettes agneau","Tagine merguez","Thé menthe"]},
     "short_description":"Dîner BBQ tentes berbères au désert d'Agafay, transport inclus.",
     "cover_url":"https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900",
     "tags":["expérience","désert","sunset","groupes"],
     "internal_note":"Désert 30 min Marrakech. Inclut transport van + chameau optionnel +150 MAD.",
     "partner_since":date(2020,2,1)},

    # Fès (5)
    {"slug":"dar-roumana","name":"Dar Roumana","city":"Fès","region":"Fès-Meknès",
     "address":"30 Derb El Amer Zkak Romane","phone":"+212 5 35 74 16 37","category":"gastronomique",
     "rating":4.85,"unit_cost":480,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":24,
     "specs":{"cuisine":"Franco-marocaine signature","ambiance":"Riad intimiste","has_terrace":True,
              "dress_code":"smart-casual","dietary":["vegetarian","gluten-free-on-request"],
              "signature_dishes":["Pigeonneau farci aux figues","Pastilla aux fruits de mer","Tarte tatin saffron"]},
     "short_description":"Table gastronomique signature de Fès, chef Younes Idrissi.",
     "cover_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900",
     "tags":["gastronomique","signature","médina","intimiste"],
     "internal_note":"Top de Fès. Capacité limitée 24 PAX. Sommelier sur demande.",
     "partner_since":date(2017,4,1),"is_preferred":True},
    {"slug":"palais-amani","name":"Palais Amani Restaurant","city":"Fès","region":"Fès-Meknès",
     "address":"12 Derb El Miter Oued Zhoun","phone":"+212 5 35 63 32 09","category":"traditionnel",
     "rating":4.6,"unit_cost":420,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":60,
     "specs":{"cuisine":"Marocaine traditionnelle revisitée","ambiance":"Palais XVIIe","has_terrace":True,
              "dress_code":"smart-casual","dietary":["vegetarian"],
              "signature_dishes":["Mrouzia","Pastilla pigeon","Mâaqouda truffée"]},
     "short_description":"Restaurant du Palais Amani, cuisine traditionnelle haut de gamme.",
     "cover_url":"https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=900",
     "tags":["palais","traditionnel","médina"],
     "internal_note":"Bon plan B si Roumana complet. Cours cuisine + dîner 850 MAD.",
     "partner_since":date(2018,5,1)},
    {"slug":"medina-cafe","name":"Café Clock Fès","city":"Fès","region":"Fès-Meknès",
     "address":"7 Derb El Magana","phone":"+212 5 35 63 78 55","category":"cosmopolite",
     "rating":4.45,"unit_cost":220,"currency":"MAD","cost_unit":"per_pax","min_pax":1,"max_pax":50,
     "specs":{"cuisine":"Marocaine fusion + camel burger","ambiance":"Café culturel rooftop",
              "has_terrace":True,"dress_code":"casual","dietary":["vegetarian","vegan"],
              "signature_dishes":["Camel burger","Soupe harira","Couscous végétarien"]},
     "short_description":"Café Clock culturel : conférences + concerts gnawa + camel burger.",
     "cover_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900",
     "tags":["culturel","casual","végétarien","branché"],
     "internal_note":"Concert gnawa jeudi soir 21h. Lunch idéal après tannerie.",
     "partner_since":date(2019,2,1)},
    {"slug":"riad-fes-restaurant","name":"L'Amandier (Riad Fès)","city":"Fès","region":"Fès-Meknès",
     "address":"5 Derb Ben Slimane Zerbtana","phone":"+212 5 35 94 76 10","category":"gastronomique",
     "rating":4.75,"unit_cost":520,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":40,
     "specs":{"cuisine":"Franco-marocaine étoilée","ambiance":"Patio Riad Fès","has_terrace":True,
              "dress_code":"smart-casual","dietary":["vegetarian","gluten-free"],
              "signature_dishes":["Tagine d'agneau aux amandes","Foie gras","Soufflé orangette"]},
     "short_description":"Resto signature du Riad Fès, table étoilée Relais & Châteaux.",
     "cover_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900",
     "tags":["étoilé","relais-châteaux","gastronomique"],
     "internal_note":"Sommelier réputé. Cave à vins française & marocaine. Menu dégustation 750 MAD.",
     "partner_since":date(2016,8,1),"is_preferred":True},
    {"slug":"nur-fes","name":"NUR","city":"Fès","region":"Fès-Meknès",
     "address":"7 Zankat Touatra","phone":"+212 5 35 74 02 18","category":"gastronomique-créative",
     "rating":4.85,"unit_cost":650,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":18,
     "specs":{"cuisine":"Cuisine d'auteur du chef Najat Kaanache","ambiance":"Maison d'auteur",
              "has_terrace":False,"dress_code":"smart","dietary":["vegetarian","vegan-on-request"],
              "signature_dishes":["Menu dégustation 7 services","Couscous noir squid ink","Pâtisseries déconstruites"]},
     "short_description":"Table d'auteur de la chef Najat Kaanache, cuisine narrative créative.",
     "cover_url":"https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=900",
     "tags":["chef-signature","créatif","intimiste","gastronomique"],
     "internal_note":"Réservation 7j à l'avance. 18 places max. WoW factor garanti.",
     "partner_since":date(2020,11,1),"is_exclusive":True},

    # Casablanca (3)
    {"slug":"rick-cafe","name":"Rick's Café","city":"Casablanca","region":"Casablanca-Settat",
     "address":"248 Boulevard Sour Jdid","phone":"+212 5 22 27 42 07","category":"thématique",
     "rating":4.4,"unit_cost":420,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":80,
     "specs":{"cuisine":"Internationale + jazz live","ambiance":"Rick's Café Casablanca (le film)",
              "has_terrace":False,"dress_code":"smart","dietary":["vegetarian"],
              "signature_dishes":["Burger Bogart","Steak au poivre","Lobster bisque"]},
     "short_description":"Recréation du Rick's Café du film Casablanca, jazz live, médina.",
     "cover_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900",
     "tags":["thématique","jazz","film","cinéphile"],
     "internal_note":"Incontournable touristique Casa. Réserver impérativement 1 semaine.",
     "partner_since":date(2014,7,1)},
    {"slug":"sqala","name":"La Sqala","city":"Casablanca","region":"Casablanca-Settat",
     "address":"Boulevard des Almohades","phone":"+212 5 22 26 09 60","category":"traditionnel",
     "rating":4.5,"unit_cost":340,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":150,
     "specs":{"cuisine":"Marocaine bord de mer","ambiance":"Bastion 18e siècle",
              "has_terrace":True,"dress_code":"casual","dietary":["vegetarian","halal"],
              "signature_dishes":["Pastilla pigeon","Tagine aux fruits de mer","Mâaqouda crevette"]},
     "short_description":"Restaurant marocain dans bastion historique, jardin face à l'océan.",
     "cover_url":"https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900",
     "tags":["traditionnel","jardin","groupes","historique"],
     "internal_note":"Lunch idéal après visite Mosquée Hassan II. Capacité 150 PAX.",
     "partner_since":date(2015,9,1)},
    {"slug":"iloli-casa","name":"Iloli Casa","city":"Casablanca","region":"Casablanca-Settat",
     "address":"19 Rue Najib Mahfoud","phone":"+212 5 22 22 13 13","category":"japonais",
     "rating":4.7,"unit_cost":560,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":40,
     "specs":{"cuisine":"Japonaise omakase","ambiance":"Sushi bar épuré","has_terrace":False,
              "dress_code":"smart-casual","dietary":["vegetarian","gluten-free"],
              "signature_dishes":["Omakase 12 pièces","Wagyu black hashi","Crème yuzu"]},
     "short_description":"Sushi bar haut de gamme Casa, omakase à la Tokyo.",
     "cover_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900",
     "tags":["japonais","sushi","branché","corporate"],
     "internal_note":"Top pour clientèle business / asiatique. Wagyu importé Australie.",
     "partner_since":date(2021,3,1)},

    # Rabat (2)
    {"slug":"saveurs-palais","name":"Le Saveurs du Palais","city":"Rabat","region":"Rabat-Salé-Kénitra",
     "address":"BP 450 Souissi (Sofitel)","phone":"+212 5 37 67 56 56","category":"gastronomique",
     "rating":4.6,"unit_cost":380,"currency":"MAD","cost_unit":"per_pax","min_pax":1,"max_pax":60,
     "specs":{"cuisine":"Franco-marocaine","ambiance":"Sofitel jardin","has_terrace":True,
              "dress_code":"smart-casual","dietary":["vegetarian","gluten-free"],
              "signature_dishes":["Pastilla","Carpaccio Saint-Pierre","Crêpe Suzette"]},
     "short_description":"Restaurant principal du Sofitel Jardin des Roses, cuisine bistronomique.",
     "cover_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900",
     "tags":["sofitel","bistronomique","jardins"],
     "internal_note":"Standard pour étape Rabat. Lunch en jardin top printemps.",
     "partner_since":date(2016,3,1)},
    {"slug":"dinarjat","name":"Dinarjat","city":"Rabat","region":"Rabat-Salé-Kénitra",
     "address":"6 Rue Belgnaoui, Médina","phone":"+212 5 37 70 42 39","category":"traditionnel",
     "rating":4.55,"unit_cost":290,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":80,
     "specs":{"cuisine":"Marocaine traditionnelle","ambiance":"Riad Médina avec Andalou",
              "has_terrace":False,"dress_code":"casual","dietary":["halal","vegetarian"],
              "signature_dishes":["Couscous royal","Méchoui agneau","Pastilla"]},
     "short_description":"Restaurant marocain dans la médina, musique andalou en soirée.",
     "cover_url":"https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=900",
     "tags":["traditionnel","médina","andalou"],
     "internal_note":"Bon prix pour groupes 30-50 PAX. Photo accueil signature.",
     "partner_since":date(2014,11,1)},

    # Essaouira / autre (3)
    {"slug":"caravane","name":"Caravane Café","city":"Essaouira","region":"Marrakech-Safi",
     "address":"2 Bis Rue Cadi Ayad","phone":"+212 5 24 78 31 11","category":"bistronomique",
     "rating":4.5,"unit_cost":240,"currency":"MAD","cost_unit":"per_pax","min_pax":1,"max_pax":40,
     "specs":{"cuisine":"Bistronomique méditerranée","ambiance":"Cour intérieure bohème",
              "has_terrace":True,"dress_code":"casual","dietary":["vegetarian","vegan"],
              "signature_dishes":["Croque-monsieur Caravane","Salade quinoa","Carrot cake"]},
     "short_description":"Bistro hippy chic au cœur d'Essaouira.",
     "cover_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900",
     "tags":["bistro","branché","hippie","médina"],
     "internal_note":"Lunch parfait avant escapade plage. Pas réservation soir.",
     "partner_since":date(2018,5,1)},
    {"slug":"chalet-plage","name":"Chalet de la Plage","city":"Essaouira","region":"Marrakech-Safi",
     "address":"Boulevard Mohammed V","phone":"+212 5 24 47 59 72","category":"poissons-fruits-de-mer",
     "rating":4.65,"unit_cost":380,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":80,
     "specs":{"cuisine":"Poissons frais bord de mer","ambiance":"Pieds dans le sable",
              "has_terrace":True,"dress_code":"casual","dietary":["pescatarian"],
              "signature_dishes":["Poisson grillé du jour","Plateau fruits de mer","Tarte aux abricots"]},
     "short_description":"Institution Essaouira pour poissons de criée, terrasse plage.",
     "cover_url":"https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900",
     "tags":["plage","poisson","institution"],
     "internal_note":"Best plage Essaouira. Poisson du marché 2 fois/jour.",
     "partner_since":date(2015,7,1),"is_preferred":True},
    {"slug":"chez-aziza","name":"Chez Aziza","city":"Chefchaouen","region":"Tanger-Tétouan-Al Hoceima",
     "address":"Plaza Outa el Hammam","phone":"+212 5 39 98 63 81","category":"traditionnel",
     "rating":4.4,"unit_cost":180,"currency":"MAD","cost_unit":"per_pax","min_pax":1,"max_pax":40,
     "specs":{"cuisine":"Berbère du Rif","ambiance":"Petite terrasse bleue","has_terrace":True,
              "dress_code":"casual","dietary":["vegetarian","halal"],
              "signature_dishes":["Bissara","Tagine kefta","Couscous merguez"]},
     "short_description":"Petite institution familiale plaza Outa el Hammam.",
     "cover_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900",
     "tags":["familial","traditionnel","authentique","budget"],
     "internal_note":"Authentique, budget-friendly. Pas de réservation, just walk-in.",
     "partner_since":date(2017,11,1)},
    {"slug":"bivouac-merzouga","name":"Bivouac dîner gala (Merzouga)","city":"Merzouga","region":"Drâa-Tafilalet",
     "address":"Erg Chebbi, Camp Sahara Luxury","phone":"+212 6 61 21 11 11","category":"gala-bivouac",
     "rating":4.85,"unit_cost":650,"currency":"MAD","cost_unit":"per_pax","min_pax":4,"max_pax":40,
     "specs":{"cuisine":"Berbère traditionnel + méchoui","ambiance":"Tentes berbères + tambours gnawa",
              "has_terrace":True,"dress_code":"casual chaud","dietary":["halal","vegetarian"],
              "signature_dishes":["Méchoui complet","Pastilla aux raisins","Spectacle gnawa"]},
     "short_description":"Bivouac gala dans les dunes : feu, méchoui, percussions, ciel étoilé.",
     "cover_url":"https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=900",
     "tags":["bivouac","gala","sahara","authentique"],
     "internal_note":"Inclus en demi-pension Camp Sahara Luxury (donc gratuit si client camp). Sinon 650 MAD/PAX.",
     "partner_since":date(2017,2,1),"is_exclusive":True},
]


# ─── ACTIVITIES ───────────────────────────────────────────────────────────────
ACTIVITIES = [
    # Marrakech (5)
    {"slug":"jardin-majorelle","name":"Jardin Majorelle + Musée YSL","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Rue Yves Saint Laurent","phone":"+212 5 24 31 30 47","category":"culturelle",
     "rating":4.7,"unit_cost":250,"currency":"MAD","cost_unit":"per_pax","min_pax":1,"max_pax":50,
     "specs":{"duration_hours":2,"difficulty":"easy","age_min":6,"group_size":50,
              "includes":["entrée Majorelle","entrée musée YSL","audioguide","guide francophone optionnel"],
              "best_season":"toute l'année","start_time":"09:00 / 14:00"},
     "short_description":"Jardin botanique d'Yves Saint Laurent + musée fashion icon Yves Saint Laurent.",
     "cover_url":"https://images.unsplash.com/photo-1539020140153-e8c237112e1d?w=900",
     "tags":["culturel","jardins","mode","photo"],
     "internal_note":"Ouverture 9h. À combiner avec Médina lunch. Pas accès berbère museum (séparé).",
     "partner_since":date(2014,1,1),"is_preferred":True},
    {"slug":"hammam-mk","name":"Rituel Hammam Royal Mansour","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Rue Abou Abbas El Sebti","phone":"+212 5 29 80 80 80","category":"bien-etre",
     "rating":4.95,"unit_cost":1450,"currency":"MAD","cost_unit":"per_pax","min_pax":1,"max_pax":4,
     "specs":{"duration_hours":3,"difficulty":"relaxant","age_min":18,"group_size":4,
              "includes":["hammam","gommage","massage 60 min","tea ritual"],
              "best_season":"toute l'année","reservation_advance_h":48},
     "short_description":"Rituel hammam complet 3h au spa du Royal Mansour.",
     "cover_url":"https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=900",
     "tags":["spa","luxe","bien-être","romantique"],
     "internal_note":"Top expérience VVIP. Réservation 48h. Couples : option salle privée +500 MAD.",
     "partner_since":date(2018,3,1),"is_exclusive":True},
    {"slug":"cours-cuisine-mk","name":"Cours de cuisine marocaine La Maison Arabe","city":"Marrakech","region":"Marrakech-Safi",
     "address":"1 Derb Assehbe","phone":"+212 5 24 38 70 10","category":"gastronomique",
     "rating":4.8,"unit_cost":650,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":12,
     "specs":{"duration_hours":4,"difficulty":"easy","age_min":12,"group_size":12,
              "includes":["marché souk avec Dada","cours en arabe-français","tablier","recettes","déjeuner"],
              "best_season":"toute l'année","start_time":"09:00"},
     "short_description":"Cours cuisine institution Maison Arabe : marché + 3 plats + déjeuner.",
     "cover_url":"https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900",
     "tags":["cuisine","interactif","famille","médina"],
     "internal_note":"3 plats au choix dans 12 (tagine, couscous, pastilla, mrouzia…). Déjeuner inclus.",
     "partner_since":date(2017,4,1),"is_preferred":True},
    {"slug":"agafay-quad","name":"Quad bike désert d'Agafay","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Route Amizmiz Km 30","phone":"+212 6 62 11 22 33","category":"aventure",
     "rating":4.6,"unit_cost":580,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":20,
     "specs":{"duration_hours":3,"difficulty":"medium","age_min":16,"group_size":20,
              "includes":["quad 250cc","casque","instructeur","thé berbère"],
              "best_season":"oct-mai","transport_from_mk":True},
     "short_description":"Excursion quad désert d'Agafay 3h, transport Marrakech inclus.",
     "cover_url":"https://images.unsplash.com/photo-1591608971376-2c9d8bafd84e?w=900",
     "tags":["aventure","quad","désert","sport"],
     "internal_note":"Transport van Marrakech inclus (30 min). Permis non requis.",
     "partner_since":date(2019,5,1)},
    {"slug":"montgolfiere-mk","name":"Vol en montgolfière au lever du soleil","city":"Marrakech","region":"Marrakech-Safi",
     "address":"Cieli Atlas","phone":"+212 6 67 88 99 00","category":"aventure",
     "rating":4.9,"unit_cost":1850,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":16,
     "specs":{"duration_hours":4,"difficulty":"easy","age_min":7,"group_size":16,
              "includes":["transport hôtel","vol 1h","petit-déjeuner berbère","certificat"],
              "best_season":"sept-mai","weather_dependent":True},
     "short_description":"Vol montgolfière 1h survol palmeraie & Atlas, petit-déj berbère post-vol.",
     "cover_url":"https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=900",
     "tags":["aventure","sunrise","romantique","panoramique"],
     "internal_note":"Météo-dépendant. Si annulé, replanifié J+1 ou remboursé. 4h45 départ hôtel.",
     "partner_since":date(2020,9,1),"is_preferred":True},

    # Fès / Meknès (4)
    {"slug":"medina-fes-tour","name":"Visite guidée Médina Fès UNESCO","city":"Fès","region":"Fès-Meknès",
     "address":"Bab Boujloud","phone":"+212 6 60 11 22 33","category":"culturelle",
     "rating":4.85,"unit_cost":350,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":15,
     "specs":{"duration_hours":4,"difficulty":"easy","age_min":6,"group_size":15,
              "includes":["guide officiel licence","entrée médersas","tannerie Chouara","Karaouiyine ext"],
              "best_season":"toute l'année","start_time":"09:00 / 14:00"},
     "short_description":"Tour 4h Médina Fès classée UNESCO : tannerie + médersas + Karaouiyine.",
     "cover_url":"https://images.unsplash.com/photo-1597212720158-e21091b5beb3?w=900",
     "tags":["culturel","unesco","médina","incontournable"],
     "internal_note":"Tannerie Chouara odeur — distribuer brins menthe. Pas accès Karaouiyine intérieur (mosquée).",
     "partner_since":date(2014,2,1),"is_preferred":True},
    {"slug":"poterie-fes","name":"Atelier poterie Aïn Nokbi","city":"Fès","region":"Fès-Meknès",
     "address":"Route de Sefrou","phone":"+212 5 35 65 11 22","category":"artisanale",
     "rating":4.55,"unit_cost":280,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":20,
     "specs":{"duration_hours":2,"difficulty":"easy","age_min":8,"group_size":20,
              "includes":["démonstration tour","initiation 30 min","souvenir poterie","thé"],
              "best_season":"toute l'année"},
     "short_description":"Visite atelier poterie traditionnelle + initiation hands-on.",
     "cover_url":"https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=900",
     "tags":["artisanat","famille","interactif","souvenir"],
     "internal_note":"Souvenir poterie cuit après séjour, expédié domicile +120 MAD.",
     "partner_since":date(2018,7,1)},
    {"slug":"volubilis-tour","name":"Volubilis & Moulay Idriss","city":"Volubilis","region":"Fès-Meknès",
     "address":"Site archéologique Volubilis","phone":"+212 5 35 54 04 11","category":"culturelle",
     "rating":4.75,"unit_cost":420,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":50,
     "specs":{"duration_hours":5,"difficulty":"easy-medium","age_min":8,"group_size":50,
              "includes":["transport van","guide site","entrées","panier-repas"],
              "best_season":"sept-juin (été chaud)","departure_from":"Fès / Meknès"},
     "short_description":"Excursion site romain Volubilis (UNESCO) + ville sainte Moulay Idriss.",
     "cover_url":"https://images.unsplash.com/photo-1591608971376-2c9d8bafd84e?w=900",
     "tags":["unesco","romain","historique","journée"],
     "internal_note":"Transport van min 4 PAX. Combinable avec Meknès en 1 journée.",
     "partner_since":date(2015,4,1)},
    {"slug":"medersa-bou-inania","name":"Médersa Bou Inania (Fès)","city":"Fès","region":"Fès-Meknès",
     "address":"Talaa Kebira","phone":"+212 5 35 63 41 12","category":"culturelle",
     "rating":4.7,"unit_cost":50,"currency":"MAD","cost_unit":"per_pax","min_pax":1,"max_pax":40,
     "specs":{"duration_hours":1,"difficulty":"easy","age_min":6,"group_size":40,
              "includes":["entrée seule (guide à part)"],"best_season":"toute l'année"},
     "short_description":"Médersa du XIVe siècle, joyau d'art mérinide ouvert aux non-musulmans.",
     "cover_url":"https://images.unsplash.com/photo-1539020140153-e8c237112e1d?w=900",
     "tags":["culturel","architecture","unesco"],
     "internal_note":"Inclus dans tour Médina si pris avec guide.",
     "partner_since":date(2014,2,1)},

    # Sahara / Atlas (4)
    {"slug":"chameau-merzouga","name":"Excursion chameau coucher de soleil","city":"Merzouga","region":"Drâa-Tafilalet",
     "address":"Erg Chebbi","phone":"+212 6 61 21 11 11","category":"aventure",
     "rating":4.85,"unit_cost":250,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":30,
     "specs":{"duration_hours":3,"difficulty":"easy","age_min":8,"group_size":30,
              "includes":["chameau","chamelier","thé sommet dune","retour camp"],
              "best_season":"oct-avril (été 45°+)","departure_time":"16:30"},
     "short_description":"Caravane chameaux à travers les dunes, sunset au sommet de l'Erg.",
     "cover_url":"https://images.unsplash.com/photo-1473165089983-8e9c84d20f4f?w=900",
     "tags":["désert","sunset","incontournable","aventure"],
     "internal_note":"Compris dans Camp Sahara Luxury. Sinon 250 MAD pour clients externes.",
     "partner_since":date(2017,2,1),"is_preferred":True},
    {"slug":"4x4-sahara","name":"4x4 Vallée du Drâa & Casbahs","city":"Ouarzazate","region":"Drâa-Tafilalet",
     "address":"Route Zagora","phone":"+212 6 62 33 44 55","category":"aventure",
     "rating":4.7,"unit_cost":3200,"currency":"MAD","cost_unit":"per_group","min_pax":2,"max_pax":4,
     "specs":{"duration_hours":8,"difficulty":"medium","age_min":10,"group_size":4,
              "includes":["4x4 + chauffeur","casbahs Tinerhir","oasis Drâa","déjeuner berbère"],
              "best_season":"sept-mai"},
     "short_description":"Journée 4x4 vallée du Drâa : casbahs, oasis, palmeraies.",
     "cover_url":"https://images.unsplash.com/photo-1591608971376-2c9d8bafd84e?w=900",
     "tags":["4x4","aventure","casbahs","oasis"],
     "internal_note":"3200 MAD pour 4 PAX max (donc 800 MAD/PAX). Land Cruiser confort.",
     "partner_since":date(2018,3,1)},
    {"slug":"trek-toubkal-2j","name":"Trek 2 jours sommet Toubkal","city":"Imlil","region":"Marrakech-Safi",
     "address":"Imlil","phone":"+212 6 64 55 66 77","category":"aventure",
     "rating":4.8,"unit_cost":2400,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":12,
     "specs":{"duration_hours":48,"difficulty":"hard","age_min":16,"group_size":12,
              "includes":["guide haute montagne","mule porteurs","refuge","repas"],
              "best_season":"avril-octobre","altitude":4167},
     "short_description":"Ascension Toubkal 4167m : 2j 1 nuit refuge, guide haute montagne.",
     "cover_url":"https://images.unsplash.com/photo-1604608672516-f1b9b1d11b04?w=900",
     "tags":["trek","montagne","sommet","sportif"],
     "internal_note":"Acclimatation conseillée. Crampons fournis hiver. Refuge spartiate.",
     "partner_since":date(2016,5,1)},
    {"slug":"vallee-ourika","name":"Vallée de l'Ourika & cascades Setti Fatma","city":"Ourika","region":"Marrakech-Safi",
     "address":"Vallée Ourika","phone":"+212 6 67 11 22 33","category":"nature",
     "rating":4.5,"unit_cost":480,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":40,
     "specs":{"duration_hours":7,"difficulty":"easy-medium","age_min":7,"group_size":40,
              "includes":["transport van","guide","randonnée 2h cascades","déjeuner berbère"],
              "best_season":"avril-novembre"},
     "short_description":"Journée Ourika : marché berbère + 7 cascades + déjeuner local.",
     "cover_url":"https://images.unsplash.com/photo-1604608672516-f1b9b1d11b04?w=900",
     "tags":["nature","famille","cascades","randonnée"],
     "internal_note":"Pas d'accès cascade #7 si crue. Marché lundi très authentique.",
     "partner_since":date(2014,4,1)},

    # Côte / autres (4)
    {"slug":"essaouira-surf","name":"Cours surf Essaouira","city":"Essaouira","region":"Marrakech-Safi",
     "address":"Plage Sidi Kaouki","phone":"+212 6 67 99 88 11","category":"sport",
     "rating":4.55,"unit_cost":350,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":10,
     "specs":{"duration_hours":2,"difficulty":"easy-medium","age_min":10,"group_size":10,
              "includes":["combinaison","planche","instructeur certifié","photos"],
              "best_season":"avril-octobre"},
     "short_description":"Initiation au surf à Sidi Kaouki, plage iconique du Maroc.",
     "cover_url":"https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=900",
     "tags":["surf","sport","plage","famille"],
     "internal_note":"Plage 25 km Essaouira (transport non inclus, +200 MAD si nécessaire).",
     "partner_since":date(2019,5,1)},
    {"slug":"kasbah-ait-ben","name":"Aït-Ben-Haddou (UNESCO)","city":"Ouarzazate","region":"Drâa-Tafilalet",
     "address":"Aït-Ben-Haddou","phone":"+212 6 65 22 11 33","category":"culturelle",
     "rating":4.8,"unit_cost":380,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":40,
     "specs":{"duration_hours":3,"difficulty":"easy","age_min":6,"group_size":40,
              "includes":["guide local","traversée Asif rivière","point photos","thé"],
              "best_season":"sept-juin"},
     "short_description":"Visite ksar UNESCO Aït-Ben-Haddou, décor Game of Thrones et Gladiator.",
     "cover_url":"https://images.unsplash.com/photo-1539020140153-e8c237112e1d?w=900",
     "tags":["unesco","cinéma","historique","photo"],
     "internal_note":"Studios Atlas Ouarzazate à 30 min — possibilité combiner journée.",
     "partner_since":date(2014,6,1),"is_preferred":True},
    {"slug":"chefchaouen-walk","name":"Visite Médina bleue Chefchaouen","city":"Chefchaouen","region":"Tanger-Tétouan-Al Hoceima",
     "address":"Plaza Outa el Hammam","phone":"+212 6 60 33 44 55","category":"culturelle",
     "rating":4.7,"unit_cost":220,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":20,
     "specs":{"duration_hours":2.5,"difficulty":"easy","age_min":6,"group_size":20,
              "includes":["guide local","kasbah","spots photos bleus","thé maison"],
              "best_season":"toute l'année"},
     "short_description":"Visite guidée 2h30 médina bleue de Chefchaouen + kasbah.",
     "cover_url":"https://images.unsplash.com/photo-1597212720158-e21091b5beb3?w=900",
     "tags":["culturel","médina","photo","instagram"],
     "internal_note":"Best lumière 10h-12h pour photos bleues. Pas guide officiel licence ici.",
     "partner_since":date(2017,8,1)},
    {"slug":"grottes-hercule","name":"Grottes d'Hercule & Cap Spartel","city":"Tanger","region":"Tanger-Tétouan-Al Hoceima",
     "address":"Cap Spartel","phone":"+212 6 67 44 55 66","category":"nature",
     "rating":4.4,"unit_cost":320,"currency":"MAD","cost_unit":"per_pax","min_pax":2,"max_pax":30,
     "specs":{"duration_hours":4,"difficulty":"easy","age_min":6,"group_size":30,
              "includes":["transport","guide","entrée grottes","thé Café Hafa"],
              "best_season":"toute l'année"},
     "short_description":"Demi-journée Tanger : Cap Spartel + Grottes d'Hercule + Café Hafa.",
     "cover_url":"https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=900",
     "tags":["nature","panoramique","historique","tanger"],
     "internal_note":"Cap Spartel = vue Atlantique/Méditerranée. Café Hafa = sunset Détroit.",
     "partner_since":date(2018,9,1)},
]


# ─── GUIDES ──────────────────────────────────────────────────────────────────
GUIDES = [
    {"slug":"karim-bennani","name":"Karim Bennani","city":"Marrakech","region":"Marrakech-Safi",
     "phone":"+212 6 61 23 45 67","email":"karim.bennani@stoursvoyages.ma","category":"culturel",
     "rating":4.95,"unit_cost":1500,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":30,
     "specs":{"languages":["FR","EN","ES","AR"],"specialties":["Médina","Histoire saadienne","Architecture mauresque"],
              "years_experience":18,"certifications":["Guide officiel licence #MK-1247","FIT certifié"],
              "regions":["Marrakech","Atlas","Agadir"]},
     "short_description":"Guide francophone star de Marrakech, 18 ans d'expérience, clients VVIP.",
     "cover_url":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900",
     "tags":["culturel","francophone","vvip"],
     "internal_note":"Guide n°1 S'TOURS. Demandé Audley + Voyageurs du Monde. Tarif fidèle 1500/j (booking 7j).",
     "partner_since":date(2014,1,1),"is_preferred":True},
    {"slug":"yasmine-alaoui","name":"Yasmine Alaoui","city":"Fès","region":"Fès-Meknès",
     "phone":"+212 6 62 34 56 78","email":"yasmine.alaoui@stoursvoyages.ma","category":"culturel",
     "rating":4.92,"unit_cost":1500,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":25,
     "specs":{"languages":["FR","EN","IT","AR"],"specialties":["Médina UNESCO","Tannerie","Karaouiyine","Mérinides"],
              "years_experience":15,"certifications":["Guide officiel licence #FE-0982"],
              "regions":["Fès","Meknès","Volubilis"]},
     "short_description":"Spécialiste médina Fès, guide italophone et anglophone très demandée.",
     "cover_url":"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900",
     "tags":["culturel","italophone","médina","femme"],
     "internal_note":"Italophone rare — booking 14j à l'avance pour clients italiens. Tour-leader certifiée.",
     "partner_since":date(2015,3,1),"is_preferred":True},
    {"slug":"hamid-ouzine","name":"Hamid Ouzine","city":"Merzouga","region":"Drâa-Tafilalet",
     "phone":"+212 6 63 45 67 89","email":"hamid.ouzine@stoursvoyages.ma","category":"désert",
     "rating":4.9,"unit_cost":1300,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":20,
     "specs":{"languages":["FR","EN","AR"],"specialties":["Désert Erg Chebbi","Astronomie","Culture berbère"],
              "years_experience":22,"certifications":["Guide désert agréé","Premiers secours"],
              "regions":["Merzouga","Erfoud","Rissani","Vallée Drâa"]},
     "short_description":"Berbère Merzouga, guide désert mythique, expert astronomie nocturne.",
     "cover_url":"https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=900",
     "tags":["désert","berbère","astronomie","aventure"],
     "internal_note":"Né dans le désert. Ses récits autour du feu = expérience unique. Inclus camps S'TOURS.",
     "partner_since":date(2017,2,1),"is_preferred":True,"is_exclusive":True},
    {"slug":"sara-laamouri","name":"Sara Laamouri","city":"Casablanca","region":"Casablanca-Settat",
     "phone":"+212 6 64 56 78 90","email":"sara.laamouri@stoursvoyages.ma","category":"culturel",
     "rating":4.7,"unit_cost":1400,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":40,
     "specs":{"languages":["FR","EN","ES","AR"],"specialties":["Architecture mauresque","Mosquée Hassan II","Art déco"],
              "years_experience":12,"certifications":["Guide officiel licence #CS-0451"],
              "regions":["Casablanca","Rabat","El Jadida"]},
     "short_description":"Guide Casa-Rabat, spécialiste architecture mauresque et art déco.",
     "cover_url":"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=900",
     "tags":["culturel","casablanca","architecture","femme"],
     "internal_note":"Très demandée pour groupes architectes / urbanistes. Hispanophone fluide.",
     "partner_since":date(2018,5,1)},
    {"slug":"omar-khettab","name":"Omar Khettab","city":"Tanger","region":"Tanger-Tétouan-Al Hoceima",
     "phone":"+212 6 65 67 89 01","email":"omar.khettab@stoursvoyages.ma","category":"culturel",
     "rating":4.65,"unit_cost":1300,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":25,
     "specs":{"languages":["FR","EN","ES","AR"],"specialties":["Tanger internationale","Bowles & écrivains","Chefchaouen"],
              "years_experience":14,"certifications":["Guide officiel licence #TA-0312"],
              "regions":["Tanger","Tétouan","Chefchaouen","Asilah"]},
     "short_description":"Spécialiste Tanger littéraire (Paul Bowles, William Burroughs).",
     "cover_url":"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900",
     "tags":["culturel","littéraire","tanger","nord"],
     "internal_note":"Connaissance encyclopédique scène artistique Tanger 1950s. Top pour clients fans.",
     "partner_since":date(2016,9,1)},
    {"slug":"aicha-benali","name":"Aïcha Benali","city":"Marrakech","region":"Marrakech-Safi",
     "phone":"+212 6 66 78 90 12","email":"aicha.benali@stoursvoyages.ma","category":"tour-leader",
     "rating":4.85,"unit_cost":1200,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":50,
     "specs":{"languages":["FR","EN","DE"],"specialties":["Tour-leader circuits","Logistique groupes","Allemand fluent"],
              "years_experience":10,"certifications":["Tour leader certifié","FAH allemand"],
              "regions":["Tout le Maroc"]},
     "short_description":"Tour-leader nationale + germanophone, idéale circuits 8-15 jours.",
     "cover_url":"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=900",
     "tags":["tour-leader","germanophone","logistique","circuits"],
     "internal_note":"Germanophone rare. Très demandée par clients DACH (Audley DE).",
     "partner_since":date(2018,11,1),"is_preferred":True},
    {"slug":"khalid-amrani","name":"Khalid Amrani","city":"Imlil","region":"Marrakech-Safi",
     "phone":"+212 6 67 89 01 23","email":"khalid.amrani@stoursvoyages.ma","category":"montagne",
     "rating":4.95,"unit_cost":1100,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":12,
     "specs":{"languages":["FR","EN","AR"],"specialties":["Trek Toubkal","Haute montagne hiver","Vallées berbères"],
              "years_experience":20,"certifications":["Guide haute montagne IFMGA","Premiers secours alpins"],
              "regions":["Atlas central","Imlil","Toubkal","Mgoun"]},
     "short_description":"Guide haute montagne IFMGA, sommet Toubkal et treks Atlas.",
     "cover_url":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900",
     "tags":["montagne","trek","sommet","sportif"],
     "internal_note":"IFMGA rare au Maroc (50 guides au total). Hiver crampons obligatoires.",
     "partner_since":date(2016,5,1),"is_exclusive":True},
    {"slug":"nadia-sebti","name":"Nadia Sebti","city":"Rabat","region":"Rabat-Salé-Kénitra",
     "phone":"+212 6 68 90 12 34","email":"nadia.sebti@stoursvoyages.ma","category":"culturel",
     "rating":4.6,"unit_cost":1300,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":30,
     "specs":{"languages":["FR","EN","AR"],"specialties":["Capitale moderne","Casbah Oudayas","Hassan & mausolée"],
              "years_experience":11,"certifications":["Guide officiel licence #RA-0789"],
              "regions":["Rabat","Salé","Volubilis"]},
     "short_description":"Guide Rabat-Salé spécialiste histoire moderne et capitale.",
     "cover_url":"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900",
     "tags":["culturel","capitale","femme"],
     "internal_note":"Standard Rabat. Souvent J1 ou J11 d'un circuit.",
     "partner_since":date(2017,3,1)},
    {"slug":"rachid-tazi","name":"Rachid Tazi","city":"Essaouira","region":"Marrakech-Safi",
     "phone":"+212 6 69 01 23 45","email":"rachid.tazi@stoursvoyages.ma","category":"culturel",
     "rating":4.7,"unit_cost":1100,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":25,
     "specs":{"languages":["FR","EN","AR"],"specialties":["Médina Essaouira","Port pêche","Histoire portugaise"],
              "years_experience":13,"certifications":["Guide officiel licence #ES-0234"],
              "regions":["Essaouira","Sidi Kaouki","Diabat"]},
     "short_description":"Guide Essaouira spécialiste médina UNESCO et port atlantique.",
     "cover_url":"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900",
     "tags":["culturel","essaouira","côte"],
     "internal_note":"Connaît tous les pêcheurs. Visite poissonnerie 5h30 du matin (offre rare).",
     "partner_since":date(2018,7,1)},
    {"slug":"marco-belhaj","name":"Marco Belhaj","city":"Marrakech","region":"Marrakech-Safi",
     "phone":"+212 6 70 12 34 56","email":"marco.belhaj@stoursvoyages.ma","category":"tour-leader",
     "rating":4.8,"unit_cost":1200,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":50,
     "specs":{"languages":["FR","EN","IT","ES"],"specialties":["Tour-leader italophone","Circuits de luxe","Coordination"],
              "years_experience":9,"certifications":["Tour leader certifié","FAH italien"],
              "regions":["Tout le Maroc"]},
     "short_description":"Tour-leader italophone + hispanophone, circuits luxe.",
     "cover_url":"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900",
     "tags":["tour-leader","italophone","luxe","circuits"],
     "internal_note":"Couvre les groupes italiens (Tour Magico, Giant Tour) — top demande.",
     "partner_since":date(2019,2,1),"is_preferred":True},
    {"slug":"zineb-fakir","name":"Zineb Fakir","city":"Fès","region":"Fès-Meknès",
     "phone":"+212 6 71 23 45 67","email":"zineb.fakir@stoursvoyages.ma","category":"culturel",
     "rating":4.55,"unit_cost":1200,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":20,
     "specs":{"languages":["FR","EN","AR"],"specialties":["Cours d'eau Boukhrareb","Souks artisanat","Cuisine tradition"],
              "years_experience":7,"certifications":["Guide officiel licence #FE-1432"],
              "regions":["Fès","Meknès"]},
     "short_description":"Jeune guide Fès, parcours artisanat et souks vivants.",
     "cover_url":"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=900",
     "tags":["culturel","artisanat","jeune"],
     "internal_note":"Plan B Fès si Yasmine indisponible. Très bonne pour groupes 5-10 PAX.",
     "partner_since":date(2020,4,1)},
    {"slug":"ahmed-bouchnaq","name":"Ahmed Bouchnaq","city":"Ouarzazate","region":"Drâa-Tafilalet",
     "phone":"+212 6 72 34 56 78","email":"ahmed.bouchnaq@stoursvoyages.ma","category":"désert",
     "rating":4.75,"unit_cost":1200,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":15,
     "specs":{"languages":["FR","EN","AR"],"specialties":["Casbahs Atlas","Studios Atlas cinéma","Vallée Drâa"],
              "years_experience":16,"certifications":["Guide local agréé","Permis 4x4 commercial"],
              "regions":["Ouarzazate","Aït-Ben-Haddou","Skoura","Drâa"]},
     "short_description":"Spécialiste casbahs et tournages cinéma (Game of Thrones, Gladiator).",
     "cover_url":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900",
     "tags":["désert","cinéma","casbahs","aventure"],
     "internal_note":"Anecdotes tournages incroyables. A travaillé sur 12 grosses productions.",
     "partner_since":date(2017,6,1),"is_preferred":True},
    {"slug":"laila-benkirane","name":"Laila Benkirane","city":"Chefchaouen","region":"Tanger-Tétouan-Al Hoceima",
     "phone":"+212 6 73 45 67 89","email":"laila.benkirane@stoursvoyages.ma","category":"culturel",
     "rating":4.5,"unit_cost":1000,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":15,
     "specs":{"languages":["FR","EN","ES"],"specialties":["Médina bleue","Photographie","Randonnée Talassemtane"],
              "years_experience":6,"certifications":["Guide local agréé"],
              "regions":["Chefchaouen","Akchour","Talassemtane"]},
     "short_description":"Guide Chefchaouen, parcours photo Instagram + rando parc Talassemtane.",
     "cover_url":"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900",
     "tags":["culturel","photo","rando","femme"],
     "internal_note":"Top pour bloggers / clients photo (parcours Instagram dédié).",
     "partner_since":date(2020,7,1)},
    {"slug":"karim-fassi","name":"Karim Fassi","city":"Casablanca","region":"Casablanca-Settat",
     "phone":"+212 6 74 56 78 90","email":"karim.fassi@stoursvoyages.ma","category":"chauffeur-guide",
     "rating":4.6,"unit_cost":1500,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":7,
     "specs":{"languages":["FR","EN","ES","AR"],"specialties":["Chauffeur-guide premium","Navette aéroport","FIT"],
              "years_experience":11,"certifications":["Permis transport touristique","Guide local"],
              "regions":["Tout le Maroc"]},
     "short_description":"Chauffeur-guide premium pour FIT 2-7 PAX, mini-van Mercedes.",
     "cover_url":"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900",
     "tags":["chauffeur-guide","fit","premium","mercedes"],
     "internal_note":"Mini-van V-Class 7 PAX. Eau bouteille, wifi, USB. Forfait 1500/j carburant inclus.",
     "partner_since":date(2018,3,1),"is_preferred":True},
    {"slug":"meryem-touijar","name":"Meryem Touijar","city":"Marrakech","region":"Marrakech-Safi",
     "phone":"+212 6 75 67 89 01","email":"meryem.touijar@stoursvoyages.ma","category":"gastronomique",
     "rating":4.85,"unit_cost":1400,"currency":"MAD","cost_unit":"per_day","min_pax":1,"max_pax":12,
     "specs":{"languages":["FR","EN","AR"],"specialties":["Food tour","Marchés souks","Cuisine de Dada"],
              "years_experience":8,"certifications":["Guide officiel #MK-1582","Food tour certifié"],
              "regions":["Marrakech","Fès"]},
     "short_description":"Guide food tour Marrakech, tours culinaires souks + chez Dada.",
     "cover_url":"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900",
     "tags":["gastronomique","food-tour","femme","souks"],
     "internal_note":"Food tour 4h Marrakech 1400/j (8-12 PAX). Inclut 6 dégustations chez vendeurs.",
     "partner_since":date(2019,9,1)},
]


def all_seed_items():
    return [
        *[("hotel", h) for h in HOTELS],
        *[("restaurant", r) for r in RESTAURANTS],
        *[("activity", a) for a in ACTIVITIES],
        *[("guide", g) for g in GUIDES],
    ]
